// Enriched Exercise Types - ported from web app (pure types, no DB dependency)

export type MovementPattern = 'push' | 'pull' | 'squat' | 'hinge' | 'lunge' | 'carry' | 'rotation' | 'isolation';
export type ExerciseTypeClassification = 'compound' | 'isolation';
export type DifficultyLevel = 'beginner' | 'intermediate' | 'advanced';
export type DataSource = 'superphysique' | 'delavier' | 'manual' | 'combined';

export const ANATOMICAL_MUSCLES = {
  pec_major_clavicular: 'Pectoral majeur claviculaire (haut)',
  pec_major_sternal: 'Pectoral majeur sternal (milieu)',
  pec_major_abdominal: 'Pectoral majeur abdominal (bas)',
  pec_minor: 'Petit pectoral',
  latissimus_dorsi: 'Grand dorsal',
  rhomboids: 'Rhomboides',
  trapezius_upper: 'Trapeze superieur',
  trapezius_mid: 'Trapeze moyen',
  trapezius_lower: 'Trapeze inferieur',
  erector_spinae: 'Erecteurs du rachis',
  teres_major: 'Grand rond',
  teres_minor: 'Petit rond',
  infraspinatus: 'Infra-epineux',
  anterior_delt: 'Deltoide anterieur',
  lateral_delt: 'Deltoide lateral',
  posterior_delt: 'Deltoide posterieur',
  rotator_cuff: 'Coiffe des rotateurs',
  biceps_long_head: 'Biceps longue portion',
  biceps_short_head: 'Biceps courte portion',
  brachialis: 'Brachial',
  brachioradialis: 'Brachio-radial',
  triceps_long_head: 'Triceps longue portion',
  triceps_lateral_head: 'Triceps vaste externe',
  triceps_medial_head: 'Triceps vaste interne',
  forearm_flexors: 'Flechisseurs avant-bras',
  forearm_extensors: 'Extenseurs avant-bras',
  quadriceps_rectus_femoris: 'Droit femoral',
  quadriceps_vastus_lateralis: 'Vaste externe',
  quadriceps_vastus_medialis: 'Vaste interne',
  quadriceps_vastus_intermedius: 'Vaste intermediaire',
  hamstrings_biceps_femoris: 'Biceps femoral',
  hamstrings_semitendinosus: 'Semi-tendineux',
  hamstrings_semimembranosus: 'Semi-membraneux',
  gluteus_maximus: 'Grand fessier',
  gluteus_medius: 'Moyen fessier',
  gluteus_minimus: 'Petit fessier',
  hip_flexors: 'Flechisseurs de hanche',
  adductors: 'Adducteurs',
  tensor_fasciae_latae: 'Tenseur du fascia lata',
  calves_gastrocnemius: 'Gastrocnemien',
  calves_soleus: 'Soleaire',
  tibialis_anterior: 'Tibial anterieur',
  rectus_abdominis: 'Grand droit',
  obliques_external: 'Obliques externes',
  obliques_internal: 'Obliques internes',
  transverse_abdominis: 'Transverse',
  serratus_anterior: 'Dentele anterieur',
} as const;

export type AnatomicalMuscle = keyof typeof ANATOMICAL_MUSCLES;

export const MUSCLE_TO_GROUP: Record<AnatomicalMuscle, string> = {
  pec_major_clavicular: 'chest',
  pec_major_sternal: 'chest',
  pec_major_abdominal: 'chest',
  pec_minor: 'chest',
  latissimus_dorsi: 'back',
  rhomboids: 'back',
  trapezius_upper: 'back',
  trapezius_mid: 'back',
  trapezius_lower: 'back',
  erector_spinae: 'back',
  teres_major: 'back',
  teres_minor: 'back',
  infraspinatus: 'back',
  anterior_delt: 'shoulders',
  lateral_delt: 'shoulders',
  posterior_delt: 'shoulders',
  rotator_cuff: 'shoulders',
  biceps_long_head: 'arms',
  biceps_short_head: 'arms',
  brachialis: 'arms',
  brachioradialis: 'arms',
  triceps_long_head: 'arms',
  triceps_lateral_head: 'arms',
  triceps_medial_head: 'arms',
  forearm_flexors: 'arms',
  forearm_extensors: 'arms',
  quadriceps_rectus_femoris: 'legs',
  quadriceps_vastus_lateralis: 'legs',
  quadriceps_vastus_medialis: 'legs',
  quadriceps_vastus_intermedius: 'legs',
  hamstrings_biceps_femoris: 'legs',
  hamstrings_semitendinosus: 'legs',
  hamstrings_semimembranosus: 'legs',
  gluteus_maximus: 'legs',
  gluteus_medius: 'legs',
  gluteus_minimus: 'legs',
  hip_flexors: 'legs',
  adductors: 'legs',
  tensor_fasciae_latae: 'legs',
  calves_gastrocnemius: 'legs',
  calves_soleus: 'legs',
  tibialis_anterior: 'legs',
  rectus_abdominis: 'core',
  obliques_external: 'core',
  obliques_internal: 'core',
  transverse_abdominis: 'core',
  serratus_anterior: 'core',
};

export function getMuscleGroup(primaryMuscles: AnatomicalMuscle[]): string {
  if (primaryMuscles.length === 0) return 'full_body';
  const group = MUSCLE_TO_GROUP[primaryMuscles[0]];
  return group || 'full_body';
}
