export type ThemeId = 'light' | 'dark' | 'navy' | 'navy-light' | 'gray' | 'gray-dark' | 'cream' | 'cream-dark' | 'fleetzen' | 'fleetzen-dark' | 'lavender' | 'lavender-dark'

export interface ThemePreset {
  id: ThemeId
  label: string
  description: string
  isDark: boolean
  // surfaces
  surfaceBg: string
  panelBg: string
  // text
  textHeading: string
  textMedium: string
  textFaint: string
  // glass card
  glassBase: string
  glassBorderAlpha: number
  cardBg: string
  cardBorder: string
  // mesh gradient tint
  meshTint: string
  // MUI overrides
  muiBackground: string
  muiPaper: string
  muiDivider: string
  muiTextPrimary: string
  muiTextSecondary: string
  // preview (pour UI settings)
  previewBg: string
  previewCard: string
  previewText: string
}

export const THEME_PRESETS: Record<ThemeId, ThemePreset> = {
  dark: {
    id: 'dark',
    label: 'Sombre',
    description: 'Sombre pour les yeux',
    isDark: true,
    surfaceBg: '#0a0a09',
    panelBg: '#1c1a14',
    textHeading: '#f5f0e6',
    textMedium: '#9a9488',
    textFaint: '#6b655c',
    glassBase: '#1c1a14',
    glassBorderAlpha: 0.12,
    cardBg: 'rgba(255,255,255,0.07)',
    cardBorder: 'rgba(255,255,255,0.1)',
    meshTint: '#0a0a0a',
    muiBackground: '#121212',
    muiPaper: '#1e1e1e',
    muiDivider: '#2c2c2c',
    muiTextPrimary: '#e1e1e1',
    muiTextSecondary: '#a0a0a0',
    previewBg: '#0a0a09',
    previewCard: '#1c1a14',
    previewText: '#f5f0e6',
  },
  light: {
    id: 'light',
    label: 'Clair',
    description: 'Lumineux et aéré',
    isDark: false,
    surfaceBg: '#f3f1ec',
    panelBg: '#ffffff',
    textHeading: '#1a1715',
    textMedium: '#7a7468',
    textFaint: '#a09888',
    glassBase: '#ffffff',
    glassBorderAlpha: 0.18,
    cardBg: '#ffffff',
    cardBorder: 'rgba(0,0,0,0.08)',
    meshTint: '#f5f3ef',
    muiBackground: '#fafafa',
    muiPaper: '#ffffff',
    muiDivider: '#e0e0e0',
    muiTextPrimary: '#1c1b1f',
    muiTextSecondary: '#49454f',
    previewBg: '#f3f1ec',
    previewCard: '#ffffff',
    previewText: '#1a1715',
  },
  navy: {
    id: 'navy',
    label: 'Bleu Marine',
    description: 'Premium et profond',
    isDark: true,
    surfaceBg: '#0b1120',
    panelBg: '#131d33',
    textHeading: '#e8eaf0',
    textMedium: '#8891a5',
    textFaint: '#5c6478',
    glassBase: '#131d33',
    glassBorderAlpha: 0.15,
    cardBg: 'rgba(255,255,255,0.06)',
    cardBorder: 'rgba(255,255,255,0.08)',
    meshTint: '#0a1020',
    muiBackground: '#0b1120',
    muiPaper: '#131d33',
    muiDivider: '#1e2d4a',
    muiTextPrimary: '#e8eaf0',
    muiTextSecondary: '#8891a5',
    previewBg: '#0b1120',
    previewCard: '#131d33',
    previewText: '#e8eaf0',
  },
  'navy-light': {
    id: 'navy-light',
    label: 'Marine Clair',
    description: 'Marine lumineux et doux',
    isDark: false,
    surfaceBg: '#e8ecf4',
    panelBg: '#f0f3fa',
    textHeading: '#1a2340',
    textMedium: '#4a5578',
    textFaint: '#7882a0',
    glassBase: '#f0f3fa',
    glassBorderAlpha: 0.20,
    cardBg: '#f0f3fa',
    cardBorder: 'rgba(0,0,0,0.07)',
    meshTint: '#e4e8f2',
    muiBackground: '#e8ecf4',
    muiPaper: '#f0f3fa',
    muiDivider: '#d0d6e4',
    muiTextPrimary: '#1a2340',
    muiTextSecondary: '#4a5578',
    previewBg: '#e8ecf4',
    previewCard: '#f0f3fa',
    previewText: '#1a2340',
  },
  gray: {
    id: 'gray',
    label: 'Gris Clair',
    description: 'Minimal et épuré',
    isDark: false,
    surfaceBg: '#f0f2f5',
    panelBg: '#ffffff',
    textHeading: '#1a1c20',
    textMedium: '#6b7280',
    textFaint: '#9ca3af',
    glassBase: '#ffffff',
    glassBorderAlpha: 0.20,
    cardBg: '#ffffff',
    cardBorder: 'rgba(0,0,0,0.07)',
    meshTint: '#eef0f4',
    muiBackground: '#f0f2f5',
    muiPaper: '#ffffff',
    muiDivider: '#e2e5ea',
    muiTextPrimary: '#1a1c20',
    muiTextSecondary: '#6b7280',
    previewBg: '#f0f2f5',
    previewCard: '#ffffff',
    previewText: '#1a1c20',
  },
  'gray-dark': {
    id: 'gray-dark',
    label: 'Gris Sombre',
    description: 'Sombre et neutre',
    isDark: true,
    surfaceBg: '#1a1c20',
    panelBg: '#25282e',
    textHeading: '#e4e6ea',
    textMedium: '#8a8f9a',
    textFaint: '#5c6170',
    glassBase: '#25282e',
    glassBorderAlpha: 0.14,
    cardBg: 'rgba(255,255,255,0.06)',
    cardBorder: 'rgba(255,255,255,0.08)',
    meshTint: '#181a1e',
    muiBackground: '#1a1c20',
    muiPaper: '#25282e',
    muiDivider: '#33373e',
    muiTextPrimary: '#e4e6ea',
    muiTextSecondary: '#8a8f9a',
    previewBg: '#1a1c20',
    previewCard: '#25282e',
    previewText: '#e4e6ea',
  },
  cream: {
    id: 'cream',
    label: 'Crème',
    description: 'Chaleureux et élégant',
    isDark: false,
    surfaceBg: '#f5f0e6',
    panelBg: '#fffdf7',
    textHeading: '#2d2418',
    textMedium: '#7a6f5e',
    textFaint: '#a09580',
    glassBase: '#fffdf7',
    glassBorderAlpha: 0.22,
    cardBg: '#fffdf7',
    cardBorder: 'rgba(0,0,0,0.07)',
    meshTint: '#f3ede0',
    muiBackground: '#f5f0e6',
    muiPaper: '#fffdf7',
    muiDivider: '#e5ddd0',
    muiTextPrimary: '#2d2418',
    muiTextSecondary: '#7a6f5e',
    previewBg: '#f5f0e6',
    previewCard: '#fffdf7',
    previewText: '#2d2418',
  },
  'cream-dark': {
    id: 'cream-dark',
    label: 'Crème Sombre',
    description: 'Chaleureux et profond',
    isDark: true,
    surfaceBg: '#1a1610',
    panelBg: '#252018',
    textHeading: '#f0e8d8',
    textMedium: '#9a8e78',
    textFaint: '#6b6050',
    glassBase: '#252018',
    glassBorderAlpha: 0.14,
    cardBg: 'rgba(255,255,255,0.06)',
    cardBorder: 'rgba(255,255,255,0.08)',
    meshTint: '#181410',
    muiBackground: '#1a1610',
    muiPaper: '#252018',
    muiDivider: '#362e22',
    muiTextPrimary: '#f0e8d8',
    muiTextSecondary: '#9a8e78',
    previewBg: '#1a1610',
    previewCard: '#252018',
    previewText: '#f0e8d8',
  },
  fleetzen: {
    id: 'fleetzen',
    label: 'Menthe Clair',
    description: 'Teal frais et professionnel',
    isDark: false,
    surfaceBg: '#eef7f6',
    panelBg: '#f7fcfb',
    textHeading: '#0f2b28',
    textMedium: '#4a706a',
    textFaint: '#7a9e98',
    glassBase: '#f7fcfb',
    glassBorderAlpha: 0.20,
    cardBg: '#f7fcfb',
    cardBorder: 'rgba(0,0,0,0.07)',
    meshTint: '#e8f5f3',
    muiBackground: '#eef7f6',
    muiPaper: '#f7fcfb',
    muiDivider: '#cce5e1',
    muiTextPrimary: '#0f2b28',
    muiTextSecondary: '#4a706a',
    previewBg: '#eef7f6',
    previewCard: '#f7fcfb',
    previewText: '#0f2b28',
  },
  'fleetzen-dark': {
    id: 'fleetzen-dark',
    label: 'Menthe Sombre',
    description: 'Teal profond et immersif',
    isDark: true,
    surfaceBg: '#0a1a18',
    panelBg: '#122624',
    textHeading: '#e0f2ef',
    textMedium: '#7eb8b0',
    textFaint: '#4d8a82',
    glassBase: '#122624',
    glassBorderAlpha: 0.14,
    cardBg: 'rgba(255,255,255,0.06)',
    cardBorder: 'rgba(255,255,255,0.08)',
    meshTint: '#091816',
    muiBackground: '#0a1a18',
    muiPaper: '#122624',
    muiDivider: '#1e3d38',
    muiTextPrimary: '#e0f2ef',
    muiTextSecondary: '#7eb8b0',
    previewBg: '#0a1a18',
    previewCard: '#122624',
    previewText: '#e0f2ef',
  },
  lavender: {
    id: 'lavender',
    label: 'Lavande Clair',
    description: 'Doux et raffiné',
    isDark: false,
    surfaceBg: '#f0eef6',
    panelBg: '#f8f7fc',
    textHeading: '#1e1a2e',
    textMedium: '#5e5680',
    textFaint: '#8a82a8',
    glassBase: '#f8f7fc',
    glassBorderAlpha: 0.20,
    cardBg: '#f8f7fc',
    cardBorder: 'rgba(0,0,0,0.07)',
    meshTint: '#ece9f4',
    muiBackground: '#f0eef6',
    muiPaper: '#f8f7fc',
    muiDivider: '#d8d4e6',
    muiTextPrimary: '#1e1a2e',
    muiTextSecondary: '#5e5680',
    previewBg: '#f0eef6',
    previewCard: '#f8f7fc',
    previewText: '#1e1a2e',
  },
  'lavender-dark': {
    id: 'lavender-dark',
    label: 'Lavande Sombre',
    description: 'Violet profond et apaisant',
    isDark: true,
    surfaceBg: '#12101c',
    panelBg: '#1e1a2e',
    textHeading: '#e8e4f2',
    textMedium: '#9a90b8',
    textFaint: '#5e5680',
    glassBase: '#1e1a2e',
    glassBorderAlpha: 0.14,
    cardBg: 'rgba(255,255,255,0.06)',
    cardBorder: 'rgba(255,255,255,0.08)',
    meshTint: '#100e1a',
    muiBackground: '#12101c',
    muiPaper: '#1e1a2e',
    muiDivider: '#2e2845',
    muiTextPrimary: '#e8e4f2',
    muiTextSecondary: '#9a90b8',
    previewBg: '#12101c',
    previewCard: '#1e1a2e',
    previewText: '#e8e4f2',
  },
}

export const ALL_THEME_IDS = Object.keys(THEME_PRESETS) as ThemeId[]
export const DARK_THEMES = new Set<ThemeId>(
  ALL_THEME_IDS.filter(id => THEME_PRESETS[id].isDark)
)

/* ── Theme Families ─────────────────────────────────────────────── */

export type ThemeFamilyId = 'default' | 'cream' | 'gray' | 'navy' | 'fleetzen' | 'lavender'
export const THEME_FAMILIES: Record<ThemeFamilyId, { label: string; light: ThemeId; dark: ThemeId }> = {
  default: { label: 'Défaut', light: 'light', dark: 'dark' },
  cream: { label: 'Crème', light: 'cream', dark: 'cream-dark' },
  gray: { label: 'Gris', light: 'gray', dark: 'gray-dark' },
  navy: { label: 'Marine', light: 'navy-light', dark: 'navy' },
  fleetzen: { label: 'Menthe', light: 'fleetzen', dark: 'fleetzen-dark' },
  lavender: { label: 'Lavande', light: 'lavender', dark: 'lavender-dark' },
}

export const ALL_FAMILY_IDS: ThemeFamilyId[] = ['default', 'cream', 'gray', 'navy', 'fleetzen', 'lavender']

/** Given a resolved ThemeId, find which family it belongs to */
export function themeFamily(id: ThemeId): ThemeFamilyId {
  for (const [fam, def] of Object.entries(THEME_FAMILIES)) {
    if (def.light === id || def.dark === id) return fam as ThemeFamilyId
  }
  return 'default'
}
