#!/usr/bin/env python3
"""
Merge free-exercise-db (873 exos) with our enriched exercises (124 exos).
- Maps muscle groups to our schema
- Translates all names to French
- Outputs a single merged JSON ready for DB seeding
"""

import json
import re
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
APP_DIR = os.path.dirname(SCRIPT_DIR)

# ── Muscle group mapping (free-exercise-db → our schema) ──
MUSCLE_GROUP_MAP = {
    'abdominals': 'core',
    'abductors': 'legs',
    'adductors': 'legs',
    'biceps': 'arms',
    'calves': 'legs',
    'chest': 'chest',
    'forearms': 'arms',
    'glutes': 'legs',
    'hamstrings': 'legs',
    'lats': 'back',
    'lower back': 'back',
    'middle back': 'back',
    'neck': 'shoulders',
    'quadriceps': 'legs',
    'shoulders': 'shoulders',
    'traps': 'back',
    'triceps': 'arms',
}

# ── Primary muscle mapping (free-exercise-db → our anatomical names) ──
PRIMARY_MUSCLE_MAP = {
    'abdominals': 'rectus_abdominis',
    'abductors': 'gluteus_maximus',
    'adductors': 'adductors',
    'biceps': 'biceps_long_head',
    'calves': 'calves_gastrocnemius',
    'chest': 'pec_major_sternal',
    'forearms': 'forearm_flexors',
    'glutes': 'gluteus_maximus',
    'hamstrings': 'hamstrings_biceps_femoris',
    'lats': 'latissimus_dorsi',
    'lower back': 'erector_spinae',
    'middle back': 'rhomboids',
    'neck': 'trapezius_upper',
    'quadriceps': 'quadriceps_rectus_femoris',
    'shoulders': 'lateral_delt',
    'traps': 'trapezius_mid',
    'triceps': 'triceps_long_head',
}

# ── Equipment mapping ──
EQUIPMENT_MAP = {
    'barbell': 'barbell',
    'dumbbell': 'dumbbell',
    'cable': 'cable',
    'machine': 'machine',
    'body only': 'bodyweight',
    'kettlebells': 'kettlebell',
    'bands': 'resistance_band',
    'medicine ball': 'medicine_ball',
    'exercise ball': 'swiss_ball',
    'e-z curl bar': 'ez_bar',
    'foam roll': 'foam_roller',
    'other': 'other',
}

# ── Difficulty mapping ──
DIFFICULTY_MAP = {
    'beginner': 'beginner',
    'intermediate': 'intermediate',
    'expert': 'advanced',
}

# ── French translations dictionary ──
# All 844 exercise names translated to French
TRANSLATIONS = {
    # ── ABDOMINALS (core) ──
    "3/4 Sit-Up": "Sit-up 3/4",
    "Ab Crunch Machine": "Crunch machine abdos",
    "Ab Roller": "Roue abdominale",
    "Advanced Kettlebell Windmill": "Moulin kettlebell avancé",
    "Air Bike": "Vélo aérien (abdos)",
    "Alternate Heel Touchers": "Toucher talons alternés",
    "Barbell Ab Rollout": "Rollout barre abdos",
    "Barbell Ab Rollout - On Knees": "Rollout barre abdos à genoux",
    "Barbell Rollout from Bench": "Rollout barre depuis banc",
    "Barbell Side Bend": "Flexion latérale barre",
    "Bent Press": "Bent press",
    "Bent-Knee Hip Raise": "Relevé de hanches genoux pliés",
    "Bosu Ball Cable Crunch With Side Bends": "Crunch poulie sur bosu avec flexions latérales",
    "Bottoms Up": "Relevé de bassin jambes tendues",
    "Butt-Ups": "Relevé de bassin inversé",
    "Cable Judo Flip": "Rotation judo poulie",
    "Cable Reverse Crunch": "Crunch inversé poulie",
    "Cable Russian Twists": "Rotation russe poulie",
    "Cable Seated Crunch": "Crunch assis poulie",
    "Cocoons": "Cocons abdominaux",
    "Cross-Body Crunch": "Crunch croisé",
    "Crunch - Hands Overhead": "Crunch mains au-dessus de la tête",
    "Crunch - Legs On Exercise Ball": "Crunch jambes sur swiss ball",
    "Crunches": "Crunchs",
    "Decline Crunch": "Crunch décliné",
    "Decline Oblique Crunch": "Crunch oblique décliné",
    "Decline Reverse Crunch": "Crunch inversé décliné",
    "Double Kettlebell Windmill": "Moulin double kettlebell",
    "Dumbbell Side Bend": "Flexion latérale haltère",
    "Elbow to Knee": "Coude au genou",
    "Exercise Ball Crunch": "Crunch sur swiss ball",
    "Exercise Ball Pull-In": "Tirage genoux sur swiss ball",
    "Flat Bench Leg Pull-In": "Tirage genoux sur banc plat",
    "Flat Bench Lying Leg Raise": "Relevé de jambes allongé sur banc",
    "Frog Sit-Ups": "Sit-ups grenouille",
    "Gorilla Chin/Crunch": "Traction-crunch gorille",
    "Hanging Pike": "Pike suspendu",
    "Jackknife Sit-Up": "Sit-up jackknife",
    "Janda Sit-Up": "Sit-up Janda",
    "Kettlebell Figure 8": "Kettlebell figure 8",
    "Kettlebell Pass Between The Legs": "Passage kettlebell entre les jambes",
    "Kettlebell Windmill": "Moulin kettlebell",
    "Knee/Hip Raise On Parallel Bars": "Relevé genoux/hanches aux barres parallèles",
    "Kneeling Cable Crunch With Alternating Oblique Twists": "Crunch poulie à genoux avec rotation oblique alternée",
    "Landmine 180's": "Rotation landmine 180°",
    "Leg Pull-In": "Tirage genoux assis",
    "Lower Back Curl": "Curl lombaire",
    "Medicine Ball Full Twist": "Rotation complète médecine-ball",
    "Oblique Crunches": "Crunchs obliques",
    "Oblique Crunches - On The Floor": "Crunchs obliques au sol",
    "One-Arm High-Pulley Cable Side Bends": "Flexion latérale poulie haute unilatérale",
    "One-Arm Medicine Ball Slam": "Slam médecine-ball unilatéral",
    "Otis-Up": "Otis-up",
    "Overhead Stretch": "Étirement bras au-dessus",
    "Pallof Press": "Pallof press",
    "Pallof Press With Rotation": "Pallof press avec rotation",
    "Plate Twist": "Rotation avec disque",
    "Press Sit-Up": "Sit-up développé",
    "Rope Crunch": "Crunch corde",
    "Scissor Kick": "Ciseaux abdominaux",
    "Seated Barbell Twist": "Rotation assis barre",
    "Seated Flat Bench Leg Pull-In": "Tirage genoux assis sur banc",
    "Seated Leg Tucks": "Flexion genoux assis",
    "Seated Overhead Stretch": "Étirement assis bras au-dessus",
    "Side Bridge": "Planche latérale",
    "Side Jackknife": "Jackknife latéral",
    "Sit-Up": "Sit-up",
    "Sledgehammer Swings": "Balancement masse",
    "Smith Machine Hip Raise": "Relevé de hanches Smith machine",
    "Spell Caster": "Spell caster",
    "Spider Crawl": "Marche araignée",
    "Standing Cable Lift": "Tirage diagonal poulie debout",
    "Standing Cable Wood Chop": "Bûcheron poulie debout",
    "Standing Lateral Stretch": "Étirement latéral debout",
    "Standing Rope Crunch": "Crunch corde debout",
    "Stomach Vacuum": "Vacuum abdominal",
    "Supine One-Arm Overhead Throw": "Lancer au-dessus unilatéral allongé",
    "Supine Two-Arm Overhead Throw": "Lancer au-dessus bilatéral allongé",
    "Suspended Fallout": "Fallout en suspension (TRX)",
    "Suspended Reverse Crunch": "Crunch inversé en suspension",
    "Toe Touchers": "Toucher d'orteils",
    "Torso Rotation": "Rotation du tronc",
    "Tuck Crunch": "Crunch groupé",
    "Weighted Ball Side Bend": "Flexion latérale avec ballon lesté",
    "Weighted Crunches": "Crunchs lestés",
    "Weighted Sit-Ups - With Bands": "Sit-ups lestés avec élastiques",
    "Wind Sprints": "Sprints abdos",

    # ── ABDUCTORS / ADDUCTORS (legs) ──
    "Adductor": "Adducteurs machine",
    "Adductor/Groin": "Adducteurs / aine",
    "Band Hip Adductions": "Adduction hanche élastique",
    "Band Pull Apart": "Écartement élastique",
    "Groiners": "Étirement aine dynamique",
    "Hip Adduction": "Adduction hanche",
    "Hip Flexion with Band": "Flexion hanche élastique",
    "IT Band Foam Rolling": "Rouleau mousse bande IT",
    "Lateral Band Walk": "Marche latérale élastique",
    "Lying Bent Leg Groin": "Étirement aine jambe pliée allongé",
    "Lying Hip Flexor": "Étirement fléchisseur hanche allongé",
    "Side Leg Raises": "Élévations latérales jambe",
    "Side Lunge": "Fente latérale",
    "Side Lying Groin Stretch": "Étirement aine latéral allongé",
    "Standing Hip Circles": "Cercles de hanche debout",
    "Standing Long Jump": "Saut en longueur debout",
    "Thigh Abductor": "Abducteurs machine",
    "Thigh Adductor": "Adducteurs machine assis",
    "Groin and Back Stretch": "Étirement aine et dos",
    "Single-Leg Hip Thrusts": "Hip thrust unilatéral",
    "Hip Extension with Bands": "Extension hanche élastique",

    # ── BICEPS (arms) ──
    "Alternate Hammer Curl": "Curl marteau alterné",
    "Alternate Incline Dumbbell Curl": "Curl incliné haltère alterné",
    "Barbell Curls Lying Against An Incline": "Curl barre contre banc incliné",
    "Body-Up": "Body-up",
    "Cable Hammer Curls - Rope Attachment": "Curl marteau poulie corde",
    "Cable Preacher Curl": "Curl pupitre poulie",
    "Close-Grip EZ-Bar Curl": "Curl barre EZ prise serrée",
    "Concentration Curls": "Curl concentré",
    "Cross Body Hammer Curl": "Curl marteau croisé",
    "Dumbbell Alternate Bicep Curl": "Curl biceps haltère alterné",
    "Dumbbell Bicep Curl": "Curl biceps haltère",
    "EZ-Bar Curl": "Curl barre EZ",
    "EZ-Bar Preacher Curl": "Curl pupitre barre EZ",
    "Flexor Incline Dumbbell Curls": "Curl incliné haltère fléchisseur",
    "Hammer Curls": "Curl marteau",
    "High Cable Curls": "Curl poulie haute",
    "Incline Hammer Curls": "Curl marteau incliné",
    "Incline Inner Biceps Curl": "Curl biceps intérieur incliné",
    "Lying Cable Curl": "Curl poulie allongé",
    "Lying Close-Grip Barbell Triceps Extension Behind The Head": "Extension triceps barre prise serrée derrière la tête allongé",
    "Lying Supine Dumbbell Curl": "Curl haltère supination allongé",
    "Machine Bicep Curl": "Curl biceps machine",
    "Machine Preacher Curls": "Curl pupitre machine",
    "One Arm Dumbbell Preacher Curl": "Curl pupitre haltère unilatéral",
    "Overhead Cable Curl": "Curl poulie au-dessus de la tête",
    "Preacher Curl - With Dumbbell": "Curl pupitre haltère",
    "Preacher Hammer Dumbbell Curl": "Curl pupitre marteau haltère",
    "Prone Incline Curl": "Curl incliné couché (spider curl)",
    "Reverse Barbell Curl": "Curl barre pronation",
    "Reverse Cable Curl": "Curl poulie pronation",
    "Seated Dumbbell Curl": "Curl haltère assis",
    "Seated Dumbbell Inner Biceps Curl": "Curl biceps intérieur assis",
    "Spider Curl": "Spider curl",
    "Standing Barbell Concentration Curl": "Curl concentré barre debout",
    "Standing Cable Curls": "Curl poulie debout",
    "Standing Concentration Curl": "Curl concentré debout",
    "Standing Dumbbell Reverse Curl": "Curl haltère pronation debout",
    "Standing Inner Biceps Curl": "Curl biceps intérieur debout",
    "Standing One-Arm Cable Curl": "Curl poulie unilatéral debout",
    "Zottman Curl": "Curl Zottman",
    "Zottman Preacher Curl": "Curl pupitre Zottman",
    "Close-Grip EZ Bar Curl with Band": "Curl barre EZ prise serrée avec élastique",
    "Dumbbell Prone Incline Curl": "Curl incliné couché haltère",
    "EZ-Bar Spider Curl": "Spider curl barre EZ",
    "Incline Cable Curl": "Curl poulie incliné",
    "One-Arm Kettlebell Clean": "Clean kettlebell unilatéral",
    "Overhead Curl": "Curl au-dessus de la tête",
    "Plate Curls": "Curl avec disque",
    "Reverse Grip Bent-Over Rows": "Rowing barre supination",
    "Ring Curls": "Curl aux anneaux",
    "Seated Close-Grip Concentration Barbell Curl": "Curl concentré barre prise serrée assis",
    "Seated One-Arm Dumbbell Bicep Curl": "Curl biceps haltère unilatéral assis",

    # ── CALVES (legs) ──
    "Balance Board": "Planche d'équilibre",
    "Barbell Seated Calf Raise": "Mollets assis barre",
    "Calf Press": "Presse à mollets",
    "Calf Press On The Leg Press Machine": "Mollets à la presse à cuisses",
    "Calf Raises - With Bands": "Mollets debout avec élastiques",
    "Calf Stretch Hands Against Wall": "Étirement mollets mains au mur",
    "Dumbbell Seated Calf Raise": "Mollets assis haltère",
    "Foot-SMR": "Automassage pied",
    "Knee Circles": "Cercles de genoux",
    "Lower Leg Curl": "Mollets tibia (leg curl inversé)",
    "Peroneals Stretch": "Étirement péroniers",
    "Peroneals-Loss": "Automassage péroniers",
    "Rocking Standing Calf Raise": "Mollets debout balancés",
    "Runner's Stretch": "Étirement du coureur",
    "Seated Calf Raise": "Mollets assis machine",
    "Smith Machine Calf Raise": "Mollets Smith machine",
    "Smith Machine Reverse Calf Raises": "Mollets inversés Smith machine",
    "Standing Barbell Calf Raise": "Mollets debout barre",
    "Standing Calf Raises": "Mollets debout",
    "Standing Dumbbell Calf Raise": "Mollets debout haltère",
    "Standing Gastrocnemius Calf Stretch": "Étirement gastrocnémien debout",
    "Standing Soleus And Achilles Stretch": "Étirement soléaire et Achille debout",
    "Ankle Circles": "Cercles de chevilles",
    "Calf Raise On A Step Box": "Mollets sur step",
    "Calf Raise On A Dumbbell": "Mollets sur haltère",
    "Dumbbell Single-Leg Calf Raise": "Mollets unilatéral haltère",
    "Single-Leg Standing Calf Raise": "Mollets debout unilatéral",

    # ── CHEST ──
    "Around The Worlds": "Tour du monde haltères",
    "Band Crossover": "Écarté élastique",
    "Barbell Bench Press - Medium Grip": "Développé couché barre prise moyenne",
    "Bench Press - Powerlifting": "Développé couché powerlifting",
    "Bench Press - With Bands": "Développé couché avec élastiques",
    "Bench Press with Short Grip": "Développé couché prise courte",
    "Board Press": "Board press",
    "Body Weight Drop": "Chute poids du corps (pompes pliométriques)",
    "Butterfly": "Butterfly (pec deck)",
    "Cable Chest Press": "Développé pectoraux poulie",
    "Cable Iron Cross": "Croix de fer poulie",
    "Chain Press": "Développé couché avec chaînes",
    "Close-Grip Barbell Bench Press": "Développé couché prise serrée",
    "Decline Barbell Bench Press": "Développé décliné barre",
    "Decline Dumbbell Bench Press": "Développé décliné haltères",
    "Decline Dumbbell Flyes": "Écarté décliné haltères",
    "Decline EZ Bar Triceps Extension": "Extension triceps barre EZ décliné",
    "Drop Push": "Pompe lâchée (pliométrique)",
    "Dumbbell Bench Press with Neutral Grip": "Développé couché haltères prise neutre",
    "Dumbbell Flyes": "Écarté couché haltères",
    "Flat Bench Cable Flyes": "Écarté couché poulie",
    "Floor Press": "Développé couché au sol",
    "Floor Press with Chains": "Développé au sol avec chaînes",
    "Hammer Grip Incline DB Bench Press": "Développé incliné haltères prise marteau",
    "Incline Cable Chest Press": "Développé incliné poulie",
    "Incline Cable Flye": "Écarté incliné poulie",
    "Incline Dumbbell Flyes": "Écarté incliné haltères",
    "Incline Dumbbell Flyes - With A Twist": "Écarté incliné haltères avec rotation",
    "Incline Dumbbell Press": "Développé incliné haltères",
    "Incline Push-Up": "Pompe inclinée (pieds surélevés)",
    "Incline Push-Up Close-Grip": "Pompe inclinée prise serrée",
    "Incline Push-Up Depth": "Pompe inclinée profonde",
    "Incline Push-Up Medium": "Pompe inclinée prise moyenne",
    "Incline Push-Up Reverse Grip": "Pompe inclinée prise inversée",
    "Incline Push-Up Wide": "Pompe inclinée prise large",
    "Isometric Chest Squeezes": "Contraction isométrique pectoraux",
    "Isometric Wipers": "Essuie-glaces isométriques",
    "JM Press": "JM press",
    "Kneeling Arm Drill": "Drill bras à genoux",
    "Leverage Chest Press": "Développé pectoraux assisté",
    "Leverage Decline Chest Press": "Développé décliné assisté",
    "Leverage Incline Chest Press": "Développé incliné assisté",
    "Low Cable Crossover": "Écarté poulie basse",
    "Machine Bench Press": "Développé couché machine",
    "Middle Chest Cable Crossover": "Écarté poulie pectoraux milieu",
    "One-Arm Flat Bench Dumbbell Flye": "Écarté couché haltère unilatéral",
    "Pin Presses": "Pin press",
    "Push Up - Close Grip": "Pompe prise serrée",
    "Push-Ups - Explosive": "Pompes explosives",
    "Push-Ups With Feet Elevated": "Pompes pieds surélevés",
    "Push-Ups With Feet On An Exercise Ball": "Pompes pieds sur swiss ball",
    "Pushups": "Pompes",
    "Pushups (Close and Wide Hand Positions)": "Pompes (prise serrée et large)",
    "Reverse Grip Bench Press": "Développé couché prise inversée",
    "Single-Arm Cable Crossover": "Écarté poulie unilatéral",
    "Smith Machine Bench Press": "Développé couché Smith machine",
    "Smith Machine Close-Grip Bench Press": "Développé couché prise serrée Smith machine",
    "Smith Machine Decline Press": "Développé décliné Smith machine",
    "Smith Machine Flat Bench Press": "Développé couché à plat Smith machine",
    "Smith Machine Incline Bench Press": "Développé incliné Smith machine",
    "Straight-Arm Dumbbell Pullover": "Pull-over haltère bras tendus",
    "Suspended Push-Up": "Pompe en suspension (TRX)",
    "Wide-Grip Barbell Bench Press": "Développé couché barre prise large",
    "Wide-Grip Decline Barbell Bench Press": "Développé décliné barre prise large",
    "Wide-Grip Decline Barbell Pullover": "Pull-over décliné barre prise large",
    "Chest Dip Alternative": "Alternative aux dips pectoraux",

    # ── FOREARMS (arms) ──
    "Barbell Behind The Back Wrist Curl": "Curl poignet barre derrière le dos",
    "Bodyweight Mid Row": "Rowing poids du corps mi-hauteur",
    "Bottoms-Up Clean From The Hang Position": "Clean kettlebell renversé depuis hanches",
    "Chin-Up": "Traction supination",
    "Dumbbell Lying Pronation": "Pronation haltère allongé",
    "Dumbbell Lying Supination": "Supination haltère allongé",
    "Dumbbell One-Arm Wrist Curl": "Curl poignet haltère unilatéral",
    "Farmer's Walk": "Marche du fermier",
    "Finger Curls": "Curl des doigts",
    "Fireman's Carry": "Portage pompier",
    "Grip Crush": "Écrasement de grip",
    "Palms-Down Dumbbell Wrist Curl Over A Bench": "Curl poignet haltère pronation sur banc",
    "Palms-Down Wrist Curl Over A Bench": "Curl poignet pronation sur banc",
    "Palms-Up Barbell Wrist Curl Over A Bench": "Curl poignet barre supination sur banc",
    "Palms-Up Dumbbell Wrist Curl Over A Bench": "Curl poignet haltère supination sur banc",
    "Radial Deviation": "Déviation radiale",
    "Rickshaw Carry": "Portage rickshaw",
    "Seated Dumbbell Palms Down Wrist Curl": "Curl poignet haltère pronation assis",
    "Seated Dumbbell Palms Up Wrist Curl": "Curl poignet haltère supination assis",
    "Seated Finger Curl": "Curl des doigts assis",
    "Seated One-Arm Dumbbell Palms Down Wrist Curl": "Curl poignet haltère pronation unilatéral assis",
    "Seated Palm-Up Barbell Wrist Curl": "Curl poignet barre supination assis",
    "Seated Two-Arm Palms-Up Low-Pulley Wrist Curl": "Curl poignet poulie basse supination assis",
    "Wrist Circles": "Cercles de poignets",
    "Wrist Roller": "Rouleau de poignet",

    # ── GLUTES (legs) ──
    "Barbell Glute Bridge": "Pont fessier barre",
    "Barbell Hip Thrust": "Hip thrust barre",
    "Cable Deadlifts With Pause": "Soulevé de terre poulie avec pause",
    "Clamshells": "Coquillages (clamshells)",
    "Donkey Kicks": "Coups de pied âne",
    "Exercise Ball Hip Thrust": "Hip thrust sur swiss ball",
    "Flutter Kicks": "Battements de jambes",
    "Glute Bridge": "Pont fessier",
    "Glute Kickback": "Extension fessier poulie",
    "Hip Thrust": "Hip thrust",
    "Hip Thrust with Pause": "Hip thrust avec pause",
    "Kettlebell Thruster": "Thruster kettlebell",
    "Pull Through": "Pull through poulie",
    "Single Leg Glute Bridge": "Pont fessier unilatéral",
    "Step-up with Knee Raise": "Step-up avec relevé de genou",
    "Stiff-Legged Barbell Deadlift": "Soulevé de terre jambes tendues barre",
    "Straight-Leg Cable Kickback": "Extension fessier poulie jambe tendue",
    "Sumo Deadlift": "Soulevé de terre sumo",
    "Sumo Deadlift with Bands": "Soulevé de terre sumo avec élastiques",
    "Walking Lunges": "Fentes marchées",
    "Wall Ball Squat": "Squat wall ball",
    "Weighted Ball Hyperextension": "Hyperextension avec ballon lesté",

    # ── HAMSTRINGS (legs) ──
    "90/90 Hamstring": "Étirement ischio-jambiers 90/90",
    "Alternate Leg Diagonal Bound": "Bond diagonal alterné",
    "Ball Leg Curl": "Leg curl sur swiss ball",
    "Barbell Deadlift": "Soulevé de terre barre",
    "Barbell Lunge": "Fente barre",
    "Barbell Step Ups": "Step-up barre",
    "Box Jump (Multiple Response)": "Box jump (enchaîné)",
    "Box Squat": "Box squat",
    "Box Squat with Bands": "Box squat avec élastiques",
    "Box Squat with Chains": "Box squat avec chaînes",
    "Butt Lift (Bridges)": "Pont fessier (bridges)",
    "Cable Pull Through": "Pull through poulie basse",
    "Chain Handle Extension": "Extension avec poignée à chaîne",
    "Chin To Chest Stretch": "Étirement menton-poitrine",
    "Clean": "Clean (épaulé)",
    "Clean Deadlift": "Soulevé de terre clean",
    "Clean Pull": "Tirage clean",
    "Clean from Blocks": "Clean depuis blocs",
    "Deficit Deadlift": "Soulevé de terre en déficit",
    "Dumbbell Lunges": "Fentes haltères",
    "Dumbbell Romanian Deadlift": "Soulevé de terre roumain haltères",
    "Dumbbell Step Ups": "Step-up haltères",
    "Electrics": "Sprints électriques",
    "Front Box Jump": "Box jump frontal",
    "Glute Ham Raise": "Glute ham raise",
    "Hang Clean": "Hang clean (épaulé suspendu)",
    "Hang Snatch": "Hang snatch (arraché suspendu)",
    "Hang Snatch - Below Knees": "Hang snatch sous les genoux",
    "Hip Thrusts With Weight": "Hip thrust lesté",
    "Inchworm": "Inchworm (chenille)",
    "Inverted Row": "Rowing inversé (Australian pull-up)",
    "Inverted Row with Straps": "Rowing inversé avec sangles",
    "Kettlebell Dead Clean": "Dead clean kettlebell",
    "Kettlebell One-Legged Deadlift": "Soulevé de terre unilatéral kettlebell",
    "Kettlebell Pistol Squat": "Pistol squat kettlebell",
    "Kettlebell Seesaw Press": "Développé balancier kettlebell",
    "Kneeling Jump Squat": "Squat sauté depuis genoux",
    "Leg Curl": "Leg curl",
    "Lying Leg Curls": "Leg curl allongé",
    "Muscle Snatch": "Muscle snatch",
    "Natural Glute Ham Raise": "Glute ham raise naturel (nordic curl)",
    "Olympic Squat": "Squat olympique",
    "One Knee To Chest": "Genou-poitrine unilatéral",
    "One-Arm Kettlebell Snatch": "Arraché kettlebell unilatéral",
    "One-Arm Kettlebell Swings": "Swing kettlebell unilatéral",
    "One-Arm Long Bar Row": "Rowing barre T unilatéral",
    "Platform Hamstring Slides": "Glissements ischio-jambiers sur plateforme",
    "Power Clean": "Power clean",
    "Power Clean from Blocks": "Power clean depuis blocs",
    "Power Snatch": "Power snatch",
    "Power Snatch from Blocks": "Power snatch depuis blocs",
    "Reverse Hyperextension": "Hyperextension inversée",
    "Romanian Deadlift With Dumbbells": "Soulevé de terre roumain haltères",
    "Romanian Deadlift from Deficit": "Soulevé de terre roumain en déficit",
    "Scissors Jump": "Sauts ciseaux",
    "Seated Hamstring": "Étirement ischio-jambiers assis",
    "Seated Leg Curl": "Leg curl assis",
    "Single Leg Push Off": "Impulsion unilatérale",
    "Single-Leg Dumbbell Deadlift": "Soulevé de terre haltère unilatéral",
    "Snatch": "Arraché (snatch)",
    "Snatch Deadlift": "Soulevé de terre arraché",
    "Snatch Pull": "Tirage arraché",
    "Snatch from Blocks": "Arraché depuis blocs",
    "Speed Deadlift": "Soulevé de terre dynamique",
    "Standing Hamstring and Calf Stretch": "Étirement ischio-jambiers et mollets debout",
    "Standing Leg Curl": "Leg curl debout",
    "Step Mill": "Step mill (escalier)",
    "Stiff Leg Barbell Good Morning": "Good morning jambes tendues",
    "Stiff-Legged Dumbbell Deadlift": "Soulevé de terre jambes tendues haltères",
    "Sumo Deadlift with Chains": "Soulevé de terre sumo avec chaînes",
    "Tire Flip": "Retournement de pneu",

    # ── LATS (back) ──
    "Cable Close Grip Seated Row": "Rowing assis poulie prise serrée",
    "Chin-Up (Lats)": "Traction supination (dorsaux)",
    "Close-Grip Front Lat Pulldown": "Tirage vertical prise serrée",
    "Close-Grip Pull-Up": "Traction prise serrée",
    "Decline Bar Pull-up": "Traction barre déclinée",
    "Dumbbell One-Arm Row": "Rowing haltère unilatéral",
    "Full Range-Of-Motion Lat Pulldown": "Tirage vertical amplitude complète",
    "Gironda Sternum Chins": "Traction sternum Gironda",
    "Machine Assisted Pull-Up": "Traction assistée machine",
    "Muscle Up": "Muscle-up",
    "One-Arm Lat Pulldown": "Tirage vertical unilatéral",
    "Pull-up": "Traction pronation",
    "Pulldown": "Tirage vertical",
    "Pullups": "Tractions",
    "Reverse Grip Pulldown": "Tirage vertical prise inversée",
    "Reverse Machine Flyes": "Oiseau inversé machine",
    "Rocky Pull-Ups/Pulldowns": "Tractions Rocky (avant-arrière)",
    "Rope Climb": "Grimper à la corde",
    "Rope Climbing": "Grimper à la corde (montée)",
    "Rope Straight-Arm Pulldown": "Tirage bras tendus corde",
    "Shotgun Row": "Rowing shotgun poulie",
    "Single-Arm Pulldown": "Tirage vertical unilatéral poulie",
    "Smith Machine Bent Over Row": "Rowing penché Smith machine",
    "Straight-Arm Pulldown": "Tirage bras tendus",
    "Underhand Cable Pulldowns": "Tirage vertical poulie prise supination",
    "V-bar Pulldown": "Tirage vertical barre V",
    "V-bar Pullup": "Traction barre V",
    "Wide Grip Pull-Up": "Traction prise large",
    "Wide-Grip Lat Pulldown": "Tirage vertical prise large",
    "Wide-Grip Rear Pull-Up": "Traction arrière prise large",
    "Cable Bar Lateral Pulldowns": "Tirage latéral poulie barre",
    "Close-Grip Lat Pull-Down": "Tirage vertical prise serrée poulie",
    "Kneeling Single-Arm High Pulley Row": "Rowing poulie haute unilatéral à genoux",
    "Negative Pull-Up": "Traction négative (excentrique)",
    "One-Arm Chin-Up": "Traction unilatérale supination",
    "Parallel Close-Grip Pull-Up": "Traction parallèle prise serrée",
    "Scapular Pull-Up": "Traction scapulaire",
    "Wide-Grip Cable Row": "Rowing poulie prise large",

    # ── LOWER BACK (back) ──
    "Atlas Stones": "Pierres d'Atlas",
    "Back Extension": "Extension lombaire (banc)",
    "Deficit Deadlift (Lower Back)": "Soulevé de terre en déficit (lombaires)",
    "Good Morning": "Good morning",
    "Hyperextensions (Back Extensions)": "Extension lombaire (hyperextension)",
    "Hyperextensions With No Hyperextension Bench": "Hyperextension sans banc",
    "Isometric Back": "Contraction isométrique dos",
    "Kettlebell Good Morning": "Good morning kettlebell",
    "Kettlebell Sumo Deadlift High Pull": "Sumo deadlift high pull kettlebell",
    "Locust": "Posture du criquet (locust)",
    "Rack Delivery": "Rack delivery",
    "Rack Pull": "Rack pull (soulevé partiel)",
    "Superman": "Superman",
    "Axle Deadlift": "Soulevé de terre axle",
    "Back Hyperextension": "Hyperextension dorsale",
    "Deadlift with Bands": "Soulevé de terre avec élastiques",
    "Deadlift with Chains": "Soulevé de terre avec chaînes",
    "Dumbbell Good Morning": "Good morning haltères",
    "Kettlebell Double Alternating Hang Clean": "Hang clean double kettlebell alterné",
    "Kettlebell Hang Clean": "Hang clean kettlebell",
    "Log Lift": "Log lift",
    "Rack Pulls with Bands": "Rack pull avec élastiques",
    "Seated Back Extension": "Extension lombaire assis",
    "Seated Good Mornings": "Good morning assis",
    "Single Leg Deadlift": "Soulevé de terre unilatéral",
    "Speed Deadlift (Lower Back)": "Soulevé de terre dynamique (lombaires)",
    "Trap Bar Deadlift": "Soulevé de terre trap bar",

    # ── MIDDLE BACK (back) ──
    "Alternating Kettlebell Row": "Rowing kettlebell alterné",
    "Band Bent-Over Row": "Rowing penché élastique",
    "Barbell Bent Over Row": "Rowing penché barre",
    "Barbell Shrug Behind The Back": "Shrug barre derrière le dos",
    "Bent Over Barbell Row": "Rowing barre penché",
    "Bent Over Two-Arm Long Bar Row": "Rowing barre T deux mains penché",
    "Bent Over Two-Dumbbell Row": "Rowing haltères deux mains penché",
    "Bent Over Two-Dumbbell Row With Palms In": "Rowing haltères prise neutre penché",
    "Cable Shrugs": "Shrugs poulie",
    "Dumbbell Incline Row": "Rowing incliné haltère",
    "Dumbbell Rear Delt Row": "Rowing deltoïde postérieur haltère",
    "Incline Bench Pull": "Tirage banc incliné",
    "Machine Row": "Rowing machine",
    "One-Arm Dumbbell Row": "Rowing haltère unilatéral",
    "Pendlay Row": "Rowing Pendlay",
    "Rack Pull (Middle Back)": "Rack pull (milieu du dos)",
    "Reverse Grip Barbell Row": "Rowing barre prise inversée",
    "Reverse Grip Incline Bench Two-Arm Dumbbell Row": "Rowing incliné haltères prise inversée",
    "Reverse Plate Curls": "Curl disque pronation",
    "Seated Cable Rows": "Rowing assis poulie",
    "Seated One-Arm Cable Pulley Rows": "Rowing poulie unilatéral assis",
    "Suspended Row": "Rowing en suspension (TRX)",
    "T-Bar Row": "Rowing barre T",
    "T-Bar Row with Handle": "Rowing barre T avec poignée",
    "Two-Arm Kettlebell Row": "Rowing kettlebell deux mains",
    "Chest Supported Dumbbell Row": "Rowing haltères support poitrine",
    "Dumbbell Row": "Rowing haltère",
    "Dumbbell Shrug": "Shrug haltère",
    "Meadows Row": "Rowing Meadows",
    "One-Arm Cable Row": "Rowing poulie unilatéral",
    "Seal Row": "Seal row (rowing allongé)",
    "Single-Arm Cable Row": "Rowing poulie unilatéral (câble)",
    "Smith Machine Row": "Rowing Smith machine",
    "Wide-Grip Standing Barbell Curl": "Curl barre prise large debout",

    # ── NECK (shoulders) ──
    "Chin To Chest Stretch (Neck)": "Étirement menton-poitrine (cou)",
    "Isometric Neck Exercise - Front And Back": "Exercice isométrique cou avant-arrière",
    "Isometric Neck Exercise - Sides": "Exercice isométrique cou latéral",
    "Lying Face Down Plate Neck Resistance": "Résistance cou avec disque face vers le bas",
    "Lying Face Up Plate Neck Resistance": "Résistance cou avec disque face vers le haut",
    "Neck-SMR": "Automassage cou",
    "Seated Head Harness Neck Resistance": "Résistance cou avec harnais assis",
    "Side Neck Stretch": "Étirement latéral du cou",

    # ── QUADRICEPS (legs) ──
    "All Fours Quad Stretch": "Étirement quadriceps quatre pattes",
    "Alternate Pistol Squat": "Pistol squat alterné",
    "Backward Drag": "Traînée arrière",
    "Barbell Front Squat": "Front squat barre",
    "Barbell Full Squat": "Squat complet barre",
    "Barbell Hack Squat": "Hack squat barre",
    "Barbell Rear Lunge": "Fente arrière barre",
    "Barbell Side Split Squat": "Squat latéral barre",
    "Barbell Squat To A Bench": "Squat barre sur banc",
    "Body Weight Squat": "Squat poids du corps",
    "Bodyweight Lunge": "Fente poids du corps",
    "Bodyweight Walking Lunge": "Fente marchée poids du corps",
    "Braced Squat": "Squat avec support",
    "Bulgarian Split Squat": "Squat bulgare",
    "Clean Shrug": "Shrug clean",
    "Close-Stance Leg Press": "Presse à cuisses pieds serrés",
    "Double Leg Butt Kick": "Coup de talon fesses bilatéral",
    "Dumbbell Front Squat": "Front squat haltères",
    "Dumbbell Goblet Squat": "Goblet squat haltère",
    "Dumbbell Lunge": "Fente haltère",
    "Dumbbell Rear Lunge": "Fente arrière haltère",
    "Dumbbell Side Lunge": "Fente latérale haltère",
    "Dumbbell Squat": "Squat haltères",
    "Dumbbell Squat To A Bench": "Squat haltères sur banc",
    "Dumbbell Walking Lunge": "Fente marchée haltères",
    "Ego Lifter": "Ego lifter",
    "Exercise Ball Leg Curl (Quad)": "Leg curl swiss ball (quadriceps)",
    "Extended Range One-Leg Press": "Presse unilatérale amplitude étendue",
    "Foam Roll Quads": "Rouleau mousse quadriceps",
    "Front Barbell Squat": "Front squat barre (avant)",
    "Front Barbell Squat To A Bench": "Front squat barre sur banc",
    "Front Leg Raises": "Élévations jambe avant",
    "Front Squat (Clean Grip)": "Front squat prise clean",
    "Front Squat (Crossed-Arms)": "Front squat bras croisés",
    "Freehand Jump Squat": "Squat sauté poids du corps",
    "Goblet Squat": "Goblet squat",
    "Hack Squat": "Hack squat machine",
    "Hip Circles (Prone)": "Cercles de hanches (couché)",
    "IT Band and Glute Stretch": "Étirement bande IT et fessiers",
    "Iliotibial Tract-Loss": "Automassage bande IT",
    "Jefferson Squat": "Squat Jefferson",
    "Jump Squat": "Squat sauté",
    "Jumping Calf Raise": "Mollets sautés",
    "Kettlebell Front Squat": "Front squat kettlebell",
    "Kettlebell Goblet Squat": "Goblet squat kettlebell",
    "Kettlebell Turkish Get-Up (Squat style)": "Relevé turc kettlebell (style squat)",
    "Knee Tuck Jump": "Saut genoux poitrine",
    "Kneeling Quad Stretch": "Étirement quadriceps à genoux",
    "Leg Extensions": "Leg extension",
    "Leg Press": "Presse à cuisses",
    "Leg Press - Narrow Stance": "Presse à cuisses pieds serrés",
    "Lunge Pass Through": "Fente avec passage",
    "Lunge Sprint": "Sprint en fentes",
    "Machine Leg Press": "Presse à cuisses machine",
    "Machine Squat": "Squat machine",
    "Narrow Stance Hack Squat": "Hack squat pieds serrés",
    "Narrow Stance Leg Press": "Presse à cuisses pieds serrés",
    "One-Arm Kettlebell Military Press To The Side": "Développé militaire kettlebell latéral",
    "One-Arm Side Deadlift": "Soulevé de terre latéral unilatéral",
    "One-Legged Cable Kickback": "Extension fessier poulie unilatérale",
    "Overhead Squat": "Overhead squat (squat au-dessus)",
    "Plie Dumbbell Squat": "Squat plié haltère",
    "Power Jerk": "Power jerk (jeté de puissance)",
    "Push Jerk": "Push jerk",
    "Push Press": "Push press",
    "Push Press - Behind the Neck": "Push press nuque",
    "Quad Stretch": "Étirement quadriceps",
    "Rear Lunge": "Fente arrière",
    "Rear Lunge with a Twist": "Fente arrière avec rotation",
    "Rickshaw Deadlift": "Soulevé de terre rickshaw",
    "Romanian Deadlift": "Soulevé de terre roumain",
    "Rope Jump": "Corde à sauter",
    "Sandbag Load": "Chargement sandbag",
    "Scissors Jump (Quad)": "Sauts ciseaux (quadriceps)",
    "Seated Barbell Good Mornings": "Good morning assis barre",
    "Seated Calf Raise (Quad)": "Mollets assis (quadriceps)",
    "Single-Arm Kettlebell Clean": "Clean kettlebell unilatéral (quadriceps)",
    "Single-Leg Leg Extension": "Leg extension unilatéral",
    "Single-Leg Press": "Presse unilatérale",
    "Single-Leg Squat": "Squat unilatéral",
    "Sled Drag - Loss": "Traînée de luge",
    "Sled Push": "Poussée de luge",
    "Smith Machine Front Squat": "Front squat Smith machine",
    "Smith Machine Leg Press": "Presse à cuisses Smith machine",
    "Smith Machine Lunge": "Fente Smith machine",
    "Smith Machine Pistol Squat": "Pistol squat Smith machine",
    "Smith Machine Squat": "Squat Smith machine",
    "Split Jerk": "Split jerk (jeté fente)",
    "Split Squat with Dumbbells": "Squat bulgare haltères",
    "Squat Jerk": "Squat jerk",
    "Squat with Bands": "Squat avec élastiques",
    "Squat with Chains": "Squat avec chaînes",
    "Squat with Plate Movers": "Squat avec déplacement de disques",
    "Step-Up": "Step-up",
    "Stiff-Legged Barbell Deadlift (Quad)": "Soulevé de terre jambes tendues (quadriceps)",
    "Tate Press": "Tate press",
    "Thigh Stretch": "Étirement cuisse",
    "Tire Flip (Quad)": "Retournement de pneu (quadriceps)",
    "Trap Bar Deadlift (Quad)": "Soulevé de terre trap bar (quadriceps)",
    "Treadmill Jogging": "Jogging tapis de course",
    "Treadmill Sprint": "Sprint tapis de course",
    "Treadmill Walking": "Marche tapis de course",
    "Two-Arm Kettlebell Clean": "Clean kettlebell deux mains",
    "Vertical Leg Press": "Presse verticale à cuisses",
    "Walking Barbell Lunge": "Fente marchée barre",
    "Weighted Sissy Squat": "Sissy squat lesté",
    "Zercher Squat": "Squat Zercher",
    "Frog Squats": "Squat grenouille",
    "Goblet Squat with Kettlebell": "Goblet squat kettlebell",
    "Landmine Squat": "Squat landmine",
    "Lateral Step-Up": "Step-up latéral",
    "Pause Squat": "Squat avec pause",
    "Pistol Squat": "Pistol squat",
    "Reverse Lunge": "Fente arrière",
    "Sissy Squat": "Sissy squat",
    "Spanish Squat": "Squat espagnol",
    "Squat": "Squat",
    "Wall Sit": "Chaise murale",

    # ── SHOULDERS ──
    "Alternating Cable Shoulder Press": "Développé épaules poulie alterné",
    "Alternating Deltoid Raise": "Élévation deltoïde alternée",
    "Alternating Floor Press": "Développé au sol alterné",
    "Alternating Hang Clean": "Hang clean alterné",
    "Alternating Kettlebell Press": "Développé kettlebell alterné",
    "Anti-Gravity Press": "Développé anti-gravité",
    "Arnold Dumbbell Press": "Développé Arnold",
    "Band Shoulder Press": "Développé épaules élastique",
    "Barbell Incline Shoulder Raise": "Élévation épaule inclinée barre",
    "Barbell Rear Delt Row": "Rowing deltoïde postérieur barre",
    "Barbell Shoulder Press": "Développé militaire barre",
    "Behind The Back Barbell Shrug": "Shrug barre derrière le dos",
    "Bradford/Rocky Presses": "Développé Bradford/Rocky",
    "Bus Drivers": "Bus drivers (rotation disque)",
    "Cable Front Raise": "Élévation frontale poulie",
    "Cable Lateral Raise": "Élévation latérale poulie",
    "Cable Rear Delt Fly": "Oiseau poulie (deltoïde postérieur)",
    "Cable Reverse Flye": "Oiseau inversé poulie",
    "Cable Shoulder Press": "Développé épaules poulie",
    "Car Drivers": "Rotation disque (car drivers)",
    "Chest Supported Lateral Raise": "Élévation latérale support poitrine",
    "Clean and Jerk": "Épaulé-jeté",
    "Clean and Press": "Épaulé-développé",
    "Clockwork Kettlebell": "Kettlebell horloge",
    "Cross-Cable Lateral Raise": "Élévation latérale poulie croisée",
    "Dumbbell Front Raise": "Élévation frontale haltère",
    "Dumbbell Incline Raise": "Élévation inclinée haltère",
    "Dumbbell Lateral Raise": "Élévation latérale haltère",
    "Dumbbell Lying One-Arm Rear Lateral Raise": "Oiseau allongé haltère unilatéral",
    "Dumbbell One-Arm Shoulder Press": "Développé épaule haltère unilatéral",
    "Dumbbell Raise": "Élévation haltère",
    "Dumbbell Rear Lateral Raise": "Élévation postérieure haltère",
    "Dumbbell Scaption": "Scaption haltère",
    "Dumbbell Shoulder Press": "Développé épaules haltères",
    "Dumbbell Upright Row": "Rowing vertical haltères",
    "External Rotation": "Rotation externe épaule",
    "External Rotation with Band": "Rotation externe élastique",
    "External Rotation with Cable": "Rotation externe poulie",
    "Face Pull": "Face pull",
    "Front Cable Raise": "Élévation frontale poulie",
    "Front Dumbbell Raise": "Élévation frontale haltère",
    "Front Plate Raise": "Élévation frontale disque",
    "Front Raise And Pullover": "Élévation frontale et pull-over",
    "Handstand Push-Ups": "Pompes en équilibre (handstand push-up)",
    "Hang Clean (Shoulder)": "Hang clean (épaules)",
    "Hang Snatch (Shoulder)": "Hang snatch (épaules)",
    "Iron Cross": "Croix de fer",
    "Kettlebell Arnold Press": "Développé Arnold kettlebell",
    "Kettlebell Clean and Press": "Épaulé-développé kettlebell",
    "Kettlebell One-Arm Press": "Développé kettlebell unilatéral",
    "Kettlebell Pirate Ships": "Bateaux pirates kettlebell",
    "Lateral Box Jump": "Box jump latéral",
    "Lateral Raise - With Bands": "Élévation latérale élastique",
    "Lateral Raise with Pause": "Élévation latérale avec pause",
    "Log Clean and Press": "Épaulé-développé log",
    "Lying Rear Delt Raise": "Oiseau allongé",
    "Machine Lateral Raise": "Élévation latérale machine",
    "Machine Shoulder (Military) Press": "Développé militaire machine",
    "One-Arm Incline Lateral Raise": "Élévation latérale inclinée unilatérale",
    "One-Arm Kettlebell Push Press": "Push press kettlebell unilatéral",
    "One-Arm Side Laterals": "Élévation latérale unilatérale",
    "Overhead Barbell Shrug": "Shrug barre au-dessus de la tête",
    "Overhead Press": "Développé militaire",
    "Overhead Slam": "Slam au-dessus",
    "Pike Press": "Développé pike (pompe pike)",
    "Power Partials": "Élévations partielles de puissance",
    "Push Press (Shoulder)": "Push press (épaules)",
    "Rear Delt Fly": "Oiseau (deltoïde postérieur)",
    "Rear Delt Raise": "Élévation deltoïde postérieur",
    "Rear Delt Row": "Rowing deltoïde postérieur",
    "Rear Delt with Dumbbell": "Oiseau haltère",
    "Reverse Flyes": "Oiseau inversé",
    "Reverse Flyes With External Rotation": "Oiseau inversé avec rotation externe",
    "Reverse Machine Flyes (Shoulder)": "Oiseau inversé machine (épaules)",
    "Rope Face Pull": "Face pull corde",
    "Round-The-World Shoulder Stretch": "Étirement épaule tour du monde",
    "Scaption With Dumbbell": "Scaption haltère",
    "Seated Barbell Military Press": "Développé militaire barre assis",
    "Seated Bent-Over Rear Delt Raise": "Oiseau penché assis",
    "Seated Dumbbell Press": "Développé haltères assis",
    "Seated Lateral Raise": "Élévation latérale assis",
    "Seated Side Lateral Raise": "Élévation latérale assis",
    "Shoulder Circles": "Cercles d'épaules",
    "Shoulder Press - With Bands": "Développé épaules élastique",
    "Shoulder Stretch": "Étirement épaule",
    "Side Lateral Raise": "Élévation latérale",
    "Single-Arm Linear Jammer": "Jammer linéaire unilatéral",
    "Smith Machine Behind Neck Press": "Développé nuque Smith machine",
    "Smith Machine Overhead Shoulder Press": "Développé épaules Smith machine",
    "Smith Machine Upright Row": "Rowing vertical Smith machine",
    "Standing Dumbbell Press": "Développé haltères debout",
    "Standing Front Barbell Raise Over Head": "Élévation frontale barre au-dessus",
    "Standing Low-Pulley Deltoid Raise": "Élévation deltoïde poulie basse debout",
    "Standing Military Press": "Développé militaire debout",
    "Standing Overhead Barbell Triceps Extension": "Extension triceps barre au-dessus debout",
    "Standing Palm-In One-Arm Dumbbell Press": "Développé haltère prise neutre unilatéral debout",
    "Straight Arm Overhead Lateral": "Élévation latérale bras tendu",
    "Upright Barbell Row": "Rowing vertical barre",
    "Upright Cable Row": "Rowing vertical poulie",
    "Upright Row - With Bands": "Rowing vertical élastique",
    "Weight Plate Front Raise": "Élévation frontale disque",
    "Wide-Grip Upright Barbell Row": "Rowing vertical barre prise large",
    "Wide Grip Standing Barbell Curl (Shoulder)": "Curl barre prise large debout (épaules)",
    "Y Raise": "Élévation en Y",
    "Lu Raise": "Lu raise",
    "Z Press": "Z press",

    # ── TRAPS (back) ──
    "Barbell Shrug": "Shrug barre",
    "Cable Shrug (Traps)": "Shrug poulie",
    "Calf-Machine Shoulder Shrug": "Shrug machine à mollets",
    "Clean Shrug (Traps)": "Shrug clean",
    "Dumbbell Shrug (Traps)": "Shrug haltères",
    "Kettlebell Sumo High Pull": "Sumo high pull kettlebell",
    "Leverage Shrug": "Shrug machine assistée",
    "Scapular Retraction": "Rétraction scapulaire",
    "Smith Machine Shrug": "Shrug Smith machine",
    "Snatch Shrug": "Shrug arraché",
    "Standing Dumbbell Shrug": "Shrug haltères debout",
    "Standing Dumbbell Upright Row": "Rowing vertical haltères debout",
    "Trap Bar Shrug": "Shrug trap bar",
    "Upright Row (Traps)": "Rowing vertical (trapèzes)",
    "Upright Row with Dumbbells": "Rowing vertical haltères",

    # ── TRICEPS (arms) ──
    "Alternating Renegade Row": "Rowing renegade alterné",
    "Band Skull Crusher": "Skull crusher élastique",
    "Bench Dips": "Dips sur banc",
    "Cable Lying Triceps Extension": "Extension triceps poulie allongé",
    "Cable One Arm Tricep Extension": "Extension triceps poulie unilatérale",
    "Cable Overhead Triceps Extension": "Extension triceps poulie au-dessus",
    "Cable Tricep Extension": "Extension triceps poulie",
    "Close Grip Bench Press": "Développé couché prise serrée (triceps)",
    "Close-Grip Dumbbell Press": "Développé haltères prise serrée",
    "Close-Grip Push-Up": "Pompe prise serrée (triceps)",
    "Decline Close-Grip Bench To Skull Crusher": "Développé décliné prise serrée vers skull crusher",
    "Decline Dumbbell Triceps Extension": "Extension triceps haltère décliné",
    "Dip Machine": "Machine à dips",
    "Dips - Close Grip": "Dips prise serrée",
    "Dips - Triceps Version": "Dips version triceps",
    "Dumbbell Floor Press": "Développé au sol haltères",
    "Dumbbell Lying Triceps Extension": "Extension triceps haltère allongé",
    "Dumbbell One-Arm Triceps Extension": "Extension triceps haltère unilatérale",
    "EZ-Bar Skullcrusher": "Skull crusher barre EZ",
    "Incline Barbell Triceps Extension": "Extension triceps barre incliné",
    "Incline Close-Grip Bench Press": "Développé incliné prise serrée",
    "Incline Dumbbell Triceps Extension": "Extension triceps haltère incliné",
    "Kneeling Cable Triceps Extension": "Extension triceps poulie à genoux",
    "Kneeling Triceps Extension": "Extension triceps à genoux",
    "Lying Close-Grip Barbell Triceps Extension": "Extension triceps barre prise serrée allongé",
    "Lying Dumbbell Tricep Extension": "Extension triceps haltère allongé",
    "Lying Triceps Press": "Presse triceps allongé",
    "One Arm Pronated Dumbbell Triceps Extension": "Extension triceps haltère pronation unilatérale",
    "Overhead Dumbbell Triceps Extension": "Extension triceps haltère au-dessus",
    "Overhead Triceps": "Extension triceps au-dessus",
    "Reverse Grip Triceps Pushdown": "Extension triceps poulie prise inversée",
    "Ring Dips": "Dips aux anneaux",
    "Seated Dumbbell Triceps Extension": "Extension triceps haltère assis",
    "Seated Triceps Press": "Presse triceps assis",
    "Smith Machine Close-Grip Bench Press (Triceps)": "Développé prise serrée Smith machine (triceps)",
    "Standing Bent-Over One-Arm Dumbbell Triceps Extension": "Extension triceps haltère unilatérale penchée debout",
    "Standing Bent-Over Two-Arm Dumbbell Triceps Extension": "Extension triceps haltères penchée debout",
    "Standing Dumbbell Triceps Extension": "Extension triceps haltère debout",
    "Standing Low-Pulley One-Arm Triceps Extension": "Extension triceps poulie basse unilatérale debout",
    "Standing One-Arm Dumbbell Triceps Extension": "Extension triceps haltère unilatérale debout",
    "Tricep Dumbbell Kickback": "Kickback triceps haltère",
    "Tricep Side Stretch": "Étirement latéral triceps",
    "Triceps Dip": "Dip triceps",
    "Triceps Overhead Extension with Rope": "Extension triceps au-dessus corde",
    "Triceps Pushdown": "Extension triceps poulie haute",
    "Triceps Pushdown - Rope Attachment": "Extension triceps poulie haute corde",
    "Triceps Pushdown - V-Bar Attachment": "Extension triceps poulie haute barre V",
    "Triceps Stretch": "Étirement triceps",
    "Two-Arm Dumbbell Kickback": "Kickback triceps haltères deux mains",
    "V-Bar Tricep Pushdown": "Extension triceps poulie barre V",
    "Weighted Bench Dip": "Dip sur banc lesté",
    "Weighted Tricep Dips": "Dips triceps lestés",

    # ── REMAINING TRANSLATIONS ──
    "Ankle On The Knee": "Cheville sur genou (étirement piriforme)",
    "Anterior Tibialis-SMR": "Automassage tibial antérieur",
    "Arm Circles": "Cercles de bras",
    "Atlas Stone Trainer": "Entraînement pierres d'Atlas",
    "Back Flyes - With Bands": "Oiseau avec élastiques",
    "Backward Medicine Ball Throw": "Lancer médecine-ball arrière",
    "Band Assisted Pull-Up": "Traction assistée élastique",
    "Band Good Morning": "Good morning élastique",
    "Band Good Morning (Pull Through)": "Good morning élastique (pull through)",
    "Barbell Guillotine Bench Press": "Développé couché guillotine",
    "Barbell Incline Bench Press - Medium Grip": "Développé incliné barre prise moyenne",
    "Barbell Walking Lunge": "Fente marchée barre",
    "Battling Ropes": "Battle ropes (cordes ondulatoires)",
    "Bear Crawl Sled Drags": "Marche de l'ours avec luge",
    "Behind Head Chest Stretch": "Étirement pectoraux mains derrière la tête",
    "Bench Jump": "Saut par-dessus banc",
    "Bench Press with Chains": "Développé couché avec chaînes",
    "Bench Sprint": "Sprint sur banc",
    "Bent-Arm Barbell Pullover": "Pull-over barre bras pliés",
    "Bent-Arm Dumbbell Pullover": "Pull-over haltère bras pliés",
    "Bent Over Dumbbell Rear Delt Raise With Head On Bench": "Oiseau haltère penché tête sur banc",
    "Bent Over Low-Pulley Side Lateral": "Élévation latérale poulie basse penché",
    "Bent Over One-Arm Long Bar Row": "Rowing barre T unilatéral penché",
    "Bicycling": "Cyclisme",
    "Bicycling, Stationary": "Vélo stationnaire",
    "Body Tricep Press": "Extension triceps poids du corps",
    "Bodyweight Flyes": "Écarté poids du corps",
    "Bodyweight Squat": "Squat poids du corps",
    "Box Skip": "Skip sur box",
    "Brachialis-SMR": "Automassage brachial",
    "Butt Lift (Bridge)": "Pont fessier",
    "Cable Deadlifts": "Soulevé de terre poulie",
    "Cable Incline Pushdown": "Extension poulie inclinée",
    "Cable Incline Triceps Extension": "Extension triceps poulie inclinée",
    "Cable Internal Rotation": "Rotation interne poulie",
    "Cable Rope Overhead Triceps Extension": "Extension triceps poulie corde au-dessus",
    "Cable Rope Rear-Delt Rows": "Rowing deltoïde postérieur corde poulie",
    "Cable Seated Lateral Raise": "Élévation latérale poulie assis",
    "Cable Wrist Curl": "Curl poignet poulie",
    "Calf Stretch Elbows Against Wall": "Étirement mollets coudes au mur",
    "Calves-SMR": "Automassage mollets",
    "Car Deadlift": "Soulevé de terre voiture (car deadlift)",
    "Carioca Quick Step": "Pas croisé rapide (carioca)",
    "Cat Stretch": "Étirement du chat",
    "Catch and Overhead Throw": "Réception et lancer au-dessus",
    "Chair Leg Extended Stretch": "Étirement jambe étendue sur chaise",
    "Chair Lower Back Stretch": "Étirement lombaires sur chaise",
    "Chair Squat": "Squat sur chaise",
    "Chair Upper Body Stretch": "Étirement haut du corps sur chaise",
    "Chest And Front Of Shoulder Stretch": "Étirement pectoraux et épaules avant",
    "Chest Push from 3 point stance": "Poussée pectorale depuis 3 appuis",
    "Chest Push (multiple response)": "Poussée pectorale (enchaîné)",
    "Chest Push (single response)": "Poussée pectorale (simple)",
    "Chest Push with Run Release": "Poussée pectorale avec sprint",
    "Chest Stretch on Stability Ball": "Étirement pectoraux sur swiss ball",
    "Child's Pose": "Posture de l'enfant",
    "Circus Bell": "Circus bell (haltère circus)",
    "Clock Push-Up": "Pompe horloge",
    "Close-Grip EZ-Bar Curl with Band": "Curl barre EZ prise serrée avec élastique",
    "Close-Grip EZ-Bar Press": "Développé barre EZ prise serrée",
    "Close-Grip EZ Bar Curl": "Curl barre EZ prise serrée",
    "Close-Grip Push-Up off of a Dumbbell": "Pompe prise serrée sur haltère",
    "Close-Grip Standing Barbell Curl": "Curl barre prise serrée debout",
    "Conan's Wheel": "Roue de Conan",
    "Cross Over - With Bands": "Écarté avec élastiques",
    "Crossover Reverse Lunge": "Fente arrière croisée",
    "Crucifix": "Crucifix (maintien latéral)",
    "Cuban Press": "Cuban press",
    "Dancer's Stretch": "Étirement du danseur",
    "Decline Push-Up": "Pompe déclinée",
    "Decline Smith Press": "Développé décliné Smith machine",
    "Depth Jump Leap": "Saut en profondeur avec bond",
    "Dips - Chest Version": "Dips version pectoraux",
    "Donkey Calf Raises": "Mollets âne (donkey calf raise)",
    "Double Kettlebell Alternating Hang Clean": "Hang clean double kettlebell alterné",
    "Double Kettlebell Jerk": "Jeté double kettlebell",
    "Double Kettlebell Push Press": "Push press double kettlebell",
    "Double Kettlebell Snatch": "Arraché double kettlebell",
    "Downward Facing Balance": "Équilibre face vers le bas",
    "Drag Curl": "Drag curl (curl glissé)",
    "Dumbbell Clean": "Clean haltère",
    "Dumbbell Incline Shoulder Raise": "Élévation épaule inclinée haltère",
    "Dumbbell Lying Rear Lateral Raise": "Élévation postérieure allongé haltère",
    "Dumbbell One-Arm Upright Row": "Rowing vertical haltère unilatéral",
    "Dumbbell Seated Box Jump": "Box jump assis avec haltères",
    "Dumbbell Seated One-Leg Calf Raise": "Mollets assis unilatéral haltère",
    "Dumbbell Tricep Extension -Pronated Grip": "Extension triceps haltère pronation",
    "Dynamic Back Stretch": "Étirement dynamique du dos",
    "Dynamic Chest Stretch": "Étirement dynamique pectoraux",
    "Elbow Circles": "Cercles de coudes",
    "Elbows Back": "Coudes en arrière (étirement)",
    "Elevated Back Lunge": "Fente arrière surélevée",
    "Elevated Cable Rows": "Rowing poulie surélevé",
    "Elliptical Trainer": "Elliptique",
    "Extended Range One-Arm Kettlebell Floor Press": "Développé au sol kettlebell unilatéral amplitude étendue",
    "Fast Skipping": "Skip rapide",
    "Floor Glute-Ham Raise": "Glute ham raise au sol",
    "Forward Drag with Press": "Traînée avant avec développé",
    "Frankenstein Squat": "Squat Frankenstein",
    "Frog Hops": "Sauts grenouille",
    "Front Cone Hops (or hurdle hops)": "Sauts de cônes (ou haies) frontaux",
    "Front Incline Dumbbell Raise": "Élévation frontale haltère inclinée",
    "Front Squats With Two Kettlebells": "Front squat double kettlebell",
    "Front Two-Dumbbell Raise": "Élévation frontale deux haltères",
    "Good Morning off Pins": "Good morning depuis pins",
    "Hamstring-SMR": "Automassage ischio-jambiers",
    "Hamstring Stretch": "Étirement ischio-jambiers",
    "Hang Clean - Below the Knees": "Hang clean sous les genoux",
    "Hanging Bar Good Morning": "Good morning barre suspendue",
    "Heaving Snatch Balance": "Snatch balance dynamique",
    "Heavy Bag Thrust": "Poussée sac de frappe",
    "Hip Circles (prone)": "Cercles de hanches (couché)",
    "Hip Lift with Band": "Relevé de hanches avec élastique",
    "Hug A Ball": "Étirement en boule",
    "Hug Knees To Chest": "Genoux à la poitrine (étirement)",
    "Hurdle Hops": "Sauts de haies",
    "Iliotibial Tract-SMR": "Automassage bande IT",
    "Incline Dumbbell Bench With Palms Facing In": "Développé incliné haltères prise neutre",
    "Incline Dumbbell Curl": "Curl incliné haltère",
    "Incline Push-Up Depth Jump": "Pompe inclinée saut en profondeur",
    "Intermediate Groin Stretch": "Étirement aine intermédiaire",
    "Intermediate Hip Flexor and Quad Stretch": "Étirement fléchisseur hanche et quadriceps intermédiaire",
    "Internal Rotation with Band": "Rotation interne élastique",
    "Iron Crosses (stretch)": "Croix de fer (étirement)",
    "Jefferson Squats": "Squat Jefferson",
    "Jerk Balance": "Jerk balance",
    "Jerk Dip Squat": "Squat dip jerk",
    "Jogging, Treadmill": "Jogging tapis de course",
    "Keg Load": "Chargement de fût",
    "Kettlebell Seated Press": "Développé assis kettlebell",
    "Kettlebell Turkish Get-Up (Lunge style)": "Relevé turc kettlebell (style fente)",
    "Kipping Muscle Up": "Muscle-up kipping",
    "Knee Across The Body": "Genou croisé vers le corps",
    "Kneeling Forearm Stretch": "Étirement avant-bras à genoux",
    "Kneeling High Pulley Row": "Rowing poulie haute à genoux",
    "Kneeling Hip Flexor": "Étirement fléchisseur hanche à genoux",
    "Kneeling Squat": "Squat à genoux",
    "Landmine Linear Jammer": "Jammer linéaire landmine",
    "Lateral Bound": "Bond latéral",
    "Lateral Cone Hops": "Sauts latéraux de cônes",
    "Latissimus Dorsi-SMR": "Automassage grand dorsal",
    "Leg-Over Floor Press": "Développé au sol jambe croisée",
    "Leg-Up Hamstring Stretch": "Étirement ischio-jambiers jambe levée",
    "Leg Lift": "Relevé de jambe",
    "Leverage Deadlift": "Soulevé de terre machine assistée",
    "Leverage High Row": "Rowing haut machine assistée",
    "Leverage Iso Row": "Rowing iso machine assistée",
    "Leverage Shoulder Press": "Développé épaules machine assistée",
    "Linear 3-Part Start Technique": "Technique de départ en 3 phases",
    "Linear Acceleration Wall Drill": "Drill d'accélération au mur",
    "Linear Depth Jump": "Saut en profondeur linéaire",
    "London Bridges": "London bridges",
    "Looking At Ceiling": "Regard au plafond (étirement cou)",
    "Low Cable Triceps Extension": "Extension triceps poulie basse",
    "Low Pulley Row To Neck": "Rowing poulie basse vers le cou",
    "Lower Back-SMR": "Automassage lombaires",
    "Lying Cambered Barbell Row": "Rowing barre cambrée allongé",
    "Lying Close-Grip Bar Curl On High Pulley": "Curl barre prise serrée poulie haute allongé",
    "Lying Close-Grip Barbell Triceps Press To Chin": "Presse triceps barre prise serrée vers le menton allongé",
    "Lying Crossover": "Crossover allongé (étirement)",
    "Lying Glute": "Étirement fessier allongé",
    "Lying Hamstring": "Étirement ischio-jambiers allongé",
    "Lying High Bench Barbell Curl": "Curl barre allongé sur banc haut",
    "Lying Machine Squat": "Squat machine allongé",
    "Lying One-Arm Lateral Raise": "Élévation latérale unilatérale allongé",
    "Lying Prone Quadriceps": "Étirement quadriceps couché",
    "Lying T-Bar Row": "Rowing barre T allongé",
    "Machine Triceps Extension": "Extension triceps machine",
    "Medicine Ball Chest Pass": "Passe poitrine médecine-ball",
    "Medicine Ball Scoop Throw": "Lancer cuillère médecine-ball",
    "Middle Back Shrug": "Shrug milieu du dos",
    "Middle Back Stretch": "Étirement milieu du dos",
    "Mixed Grip Chin": "Traction prise mixte",
    "Monster Walk": "Marche monstre (élastique)",
    "Moving Claw Series": "Série de griffes en mouvement",
    "Narrow Stance Hack Squats": "Hack squat pieds serrés",
    "Narrow Stance Squats": "Squat pieds serrés",
    "Neck Press": "Neck press (développé cou)",
    "On-Your-Back Quad Stretch": "Étirement quadriceps sur le dos",
    "On Your Side Quad Stretch": "Étirement quadriceps sur le côté",
    "One-Arm Kettlebell Clean and Jerk": "Épaulé-jeté kettlebell unilatéral",
    "One-Arm Kettlebell Floor Press": "Développé au sol kettlebell unilatéral",
    "One-Arm Kettlebell Jerk": "Jeté kettlebell unilatéral",
    "One-Arm Kettlebell Para Press": "Para press kettlebell unilatéral",
    "One-Arm Kettlebell Row": "Rowing kettlebell unilatéral",
    "One-Arm Kettlebell Split Jerk": "Split jerk kettlebell unilatéral",
    "One-Arm Kettlebell Split Snatch": "Split snatch kettlebell unilatéral",
    "One-Arm Open Palm Kettlebell Clean": "Clean kettlebell paume ouverte unilatéral",
    "One-Arm Overhead Kettlebell Squats": "Squat overhead kettlebell unilatéral",
    "One Arm Against Wall": "Étirement bras contre le mur",
    "One Arm Chin-Up": "Traction unilatérale",
    "One Arm Dumbbell Bench Press": "Développé couché haltère unilatéral",
    "One Arm Floor Press": "Développé au sol unilatéral",
    "One Arm Lat Pulldown": "Tirage vertical unilatéral",
    "One Arm Supinated Dumbbell Triceps Extension": "Extension triceps haltère supination unilatérale",
    "One Half Locust": "Demi posture du criquet",
    "One Handed Hang": "Suspension unilatérale",
    "One Leg Barbell Squat": "Squat barre unilatéral",
    "Open Palm Kettlebell Clean": "Clean kettlebell paume ouverte",
    "Overhead Lat": "Étirement grand dorsal au-dessus",
    "Parallel Bar Dip": "Dips aux barres parallèles",
    "Pelvic Tilt Into Bridge": "Bascule du bassin en pont",
    "Peroneals-SMR": "Automassage péroniers",
    "Physioball Hip Bridge": "Pont de hanches sur swiss ball",
    "Piriformis-SMR": "Automassage piriforme",
    "Plate Pinch": "Pincement de disques",
    "Plyo Kettlebell Pushups": "Pompes pliométriques kettlebell",
    "Plyo Push-up": "Pompe pliométrique",
    "Posterior Tibialis Stretch": "Étirement tibial postérieur",
    "Power Stairs": "Escaliers de puissance",
    "Prone Manual Hamstring": "Ischio-jambiers manuel couché",
    "Prowler Sprint": "Sprint prowler (luge poussée)",
    "Push-Up Wide": "Pompe prise large",
    "Push-Ups - Close Triceps Position": "Pompes position triceps serrée",
    "Push Up to Side Plank": "Pompe vers planche latérale",
    "Pyramid": "Pyramide (exercice)",
    "Quadriceps-SMR": "Automassage quadriceps",
    "Quick Leap": "Bond rapide",
    "Rack Pull with Bands": "Rack pull avec élastiques",
    "Rack Pulls": "Rack pulls",
    "Rear Leg Raises": "Élévations jambe arrière",
    "Recumbent Bike": "Vélo couché",
    "Return Push from Stance": "Poussée retour depuis position",
    "Reverse Band Bench Press": "Développé couché élastique inversé",
    "Reverse Band Box Squat": "Box squat élastique inversé",
    "Reverse Band Deadlift": "Soulevé de terre élastique inversé",
    "Reverse Band Power Squat": "Power squat élastique inversé",
    "Reverse Band Sumo Deadlift": "Soulevé de terre sumo élastique inversé",
    "Reverse Barbell Preacher Curls": "Curl pupitre barre pronation",
    "Reverse Triceps Bench Press": "Développé couché triceps inversé",
    "Rhomboids-SMR": "Automassage rhomboïdes",
    "Rocket Jump": "Saut fusée",
    "Rope Jumping": "Saut à la corde",
    "Round The World Shoulder Stretch": "Étirement épaule tour du monde",
    "Rowing, Stationary": "Rameur stationnaire",
    "Running, Treadmill": "Course tapis de course",
    "Seated Band Hamstring Curl": "Leg curl assis élastique",
    "Seated Bent-Over One-Arm Dumbbell Triceps Extension": "Extension triceps haltère unilatérale penché assis",
    "Seated Bent-Over Two-Arm Dumbbell Triceps Extension": "Extension triceps haltères penché assis",
    "Seated Biceps": "Étirement biceps assis",
    "Seated Cable Shoulder Press": "Développé épaules poulie assis",
    "Seated Calf Stretch": "Étirement mollets assis",
    "Seated Dumbbell Palms-Down Wrist Curl": "Curl poignet haltère pronation assis",
    "Seated Dumbbell Palms-Up Wrist Curl": "Curl poignet haltère supination assis",
    "Seated Floor Hamstring Stretch": "Étirement ischio-jambiers au sol assis",
    "Seated Front Deltoid": "Étirement deltoïde avant assis",
    "Seated Glute": "Étirement fessier assis",
    "Seated Hamstring and Calf Stretch": "Étirement ischio-jambiers et mollets assis",
    "Seated One-Arm Dumbbell Palms-Down Wrist Curl": "Curl poignet haltère pronation unilatéral assis",
    "Seated One-Arm Dumbbell Palms-Up Wrist Curl": "Curl poignet haltère supination unilatéral assis",
    "Seated One-arm Cable Pulley Rows": "Rowing poulie unilatéral assis",
    "Seated Palms-Down Barbell Wrist Curl": "Curl poignet barre pronation assis",
    "See-Saw Press (Alternating Side Press)": "Développé balancier alterné",
    "Shoulder Raise": "Élévation d'épaules",
    "Side-Lying Floor Stretch": "Étirement au sol sur le côté",
    "Side Hop-Sprint": "Saut latéral-sprint",
    "Side Laterals to Front Raise": "Élévation latérale vers frontale",
    "Side Standing Long Jump": "Saut en longueur latéral debout",
    "Side To Side Chins": "Tractions latérales alternées",
    "Side Wrist Pull": "Traction latérale poignet",
    "Side to Side Box Shuffle": "Shuffle latéral sur box",
    "Single-Arm Push-Up": "Pompe unilatérale",
    "Single-Cone Sprint Drill": "Drill sprint cône unique",
    "Single-Leg High Box Squat": "Box squat haut unilatéral",
    "Single-Leg Hop Progression": "Progression sauts unilatéraux",
    "Single-Leg Lateral Hop": "Saut latéral unilatéral",
    "Single-Leg Stride Jump": "Saut foulée unilatéral",
    "Single Dumbbell Raise": "Élévation haltère unique",
    "Single Leg Butt Kick": "Talon-fesse unilatéral",
    "Single Leg Push-off": "Impulsion unilatérale",
    "Sit Squats": "Squat assis",
    "Skating": "Patin (exercice)",
    "Sled Drag - Harness": "Traînée de luge avec harnais",
    "Sled Overhead Backward Walk": "Marche arrière luge bras au-dessus",
    "Sled Overhead Triceps Extension": "Extension triceps luge au-dessus",
    "Sled Reverse Flye": "Oiseau inversé luge",
    "Sled Row": "Rowing luge",
    "Smith Incline Shoulder Raise": "Élévation épaule inclinée Smith machine",
    "Smith Machine Behind the Back Shrug": "Shrug Smith machine derrière le dos",
    "Smith Machine Hang Power Clean": "Hang power clean Smith machine",
    "Smith Machine One-Arm Upright Row": "Rowing vertical unilatéral Smith machine",
    "Smith Machine Stiff-Legged Deadlift": "Soulevé de terre jambes tendues Smith machine",
    "Smith Single-Leg Split Squat": "Squat bulgare Smith machine",
    "Snatch Balance": "Snatch balance",
    "Speed Band Overhead Triceps": "Extension triceps élastique au-dessus",
    "Speed Box Squat": "Box squat dynamique",
    "Speed Squats": "Squat dynamique",
    "Spinal Stretch": "Étirement spinal",
    "Split Clean": "Split clean",
    "Split Jump": "Saut en fente",
    "Split Snatch": "Split snatch",
    "Split Squats": "Squat bulgare",
    "Squats - With Bands": "Squat avec élastiques",
    "Stairmaster": "Stairmaster (escalier)",
    "Standing Alternating Dumbbell Press": "Développé haltère alterné debout",
    "Standing Barbell Press Behind Neck": "Développé barre nuque debout",
    "Standing Biceps Cable Curl": "Curl biceps poulie debout",
    "Standing Biceps Stretch": "Étirement biceps debout",
    "Standing Bradford Press": "Bradford press debout",
    "Standing Cable Chest Press": "Développé pectoraux poulie debout",
    "Standing Dumbbell Straight-Arm Front Delt Raise Above Head": "Élévation frontale bras tendus au-dessus haltère debout",
    "Standing Elevated Quad Stretch": "Étirement quadriceps surélevé debout",
    "Standing Hip Flexors": "Étirement fléchisseurs hanche debout",
    "Standing Inner-Biceps Curl": "Curl biceps intérieur debout",
    "Standing Olympic Plate Hand Squeeze": "Pincement disque olympique debout",
    "Standing One-Arm Dumbbell Curl Over Incline Bench": "Curl haltère unilatéral sur banc incliné debout",
    "Standing Palms-In Dumbbell Press": "Développé haltères prise neutre debout",
    "Standing Palms-Up Barbell Behind The Back Wrist Curl": "Curl poignet barre supination derrière le dos debout",
    "Standing Pelvic Tilt": "Bascule du bassin debout",
    "Standing Toe Touches": "Toucher d'orteils debout",
    "Standing Towel Triceps Extension": "Extension triceps serviette debout",
    "Standing Two-Arm Overhead Throw": "Lancer au-dessus deux mains debout",
    "Star Jump": "Saut étoile",
    "Straight Bar Bench Mid Rows": "Rowing barre droite milieu sur banc",
    "Straight Raises on Incline Bench": "Élévations bras tendus sur banc incliné",
    "Stride Jump Crossover": "Saut foulée croisé",
    "Supine Chest Throw": "Lancer poitrine allongé",
    "Suspended Split Squat": "Squat bulgare en suspension (TRX)",
    "Svend Press": "Svend press (presse avec disques)",
    "The Straddle": "Grand écart (straddle)",
    "Trail Running/Walking": "Course/marche en sentier",
    "Two-Arm Dumbbell Preacher Curl": "Curl pupitre haltères deux mains",
    "Two-Arm Kettlebell Jerk": "Jeté kettlebell deux mains",
    "Two-Arm Kettlebell Military Press": "Développé militaire kettlebell deux mains",
    "Upper Back-Leg Grab": "Étirement dos-jambe (attrape-jambe)",
    "Upper Back Stretch": "Étirement haut du dos",
    "Upward Stretch": "Étirement vers le haut",
    "V-Bar Pulldown": "Tirage vertical barre V",
    "V-Bar Pullup": "Traction barre V",
    "Vertical Swing": "Swing vertical",
    "Walking, Treadmill": "Marche tapis de course",
    "Weighted Jump Squat": "Squat sauté lesté",
    "Weighted Pull Ups": "Tractions lestées",
    "Weighted Squat": "Squat lesté",
    "Wide-Grip Pulldown Behind The Neck": "Tirage vertical nuque prise large",
    "Wide Stance Barbell Squat": "Squat barre stance large",
    "Wide Stance Stiff Legs": "Soulevé de terre jambes tendues stance large",
    "Windmills": "Moulins (windmill)",
    "World's Greatest Stretch": "Le plus grand étirement du monde",
    "Wrist Rotations with Straight Bar": "Rotations poignet barre droite",
    "Yoke Walk": "Marche avec joug (yoke walk)",
    "Zercher Squats": "Squat Zercher",
}


def slugify(name: str) -> str:
    """Convert exercise name to kebab-case ID."""
    s = name.lower().strip()
    s = re.sub(r'[^a-z0-9\s-]', '', s)
    s = re.sub(r'[\s]+', '-', s)
    s = re.sub(r'-+', '-', s)
    return s.strip('-')


def map_primary_muscles(muscles: list[str]) -> list[str]:
    """Map free-exercise-db muscle names to our anatomical names."""
    return [PRIMARY_MUSCLE_MAP.get(m, m) for m in muscles]


def map_equipment(equip=None):
    """Map equipment string to our equipment list."""
    if not equip or equip == 'None':
        return ['bodyweight']
    return [EQUIPMENT_MAP.get(equip, equip)]


def convert_exercise(ex: dict) -> dict:
    """Convert a free-exercise-db exercise to our schema."""
    name_en = ex['name']
    name_fr = TRANSLATIONS.get(name_en, name_en)  # Fallback to English if missing
    primary_muscle = ex['primaryMuscles'][0] if ex['primaryMuscles'] else 'other'
    muscle_group = MUSCLE_GROUP_MAP.get(primary_muscle, 'full_body')

    return {
        'id': slugify(name_en),
        'name_fr': name_fr,
        'name_en': name_en,
        'aliases': [],
        'movement_pattern': None,
        'exercise_type': ex.get('mechanic') or None,  # compound/isolation
        'muscle_group': muscle_group,
        'primary_muscles': map_primary_muscles(ex.get('primaryMuscles', [])),
        'secondary_muscles': map_primary_muscles(ex.get('secondaryMuscles', [])),
        'stabilizers': [],
        'equipment': map_equipment(ex.get('equipment')),
        'equipment_alternatives': [],
        'good_for': None,
        'bad_for': None,
        'modifications': [],
        'difficulty': DIFFICULTY_MAP.get(ex.get('level', ''), 'intermediate'),
        'technique_cues': [],
        'common_mistakes': [],
        'instructions': ex.get('instructions', []),
        'source': 'manual',
        'image_url': None,
        'video_url': None,
    }


def main():
    # Load source data
    with open(os.path.join('/tmp', 'free-exercises.json')) as f:
        new_exercises = json.load(f)

    with open(os.path.join(APP_DIR, 'data', 'exercises-enriched.json')) as f:
        existing_data = json.load(f)
        existing_exercises = existing_data['exercises']

    # Build set of existing names (lowercased) for dedup
    existing_names = set(e['name_en'].lower().strip() for e in existing_exercises)

    # Convert new exercises, dedup by name
    seen = set()
    converted = []
    untranslated = []

    for ex in new_exercises:
        name = ex['name']
        if name in seen or name.lower().strip() in existing_names:
            continue
        seen.add(name)

        entry = convert_exercise(ex)
        converted.append(entry)

        if name not in TRANSLATIONS:
            untranslated.append(name)

    # Merge: existing (enriched) first, then new
    merged = existing_exercises + converted

    # Output
    output = {
        'version': '2.0.0',
        'source': 'SuperPhysique/Delavier + free-exercise-db',
        'exercises': merged,
    }

    out_path = os.path.join(APP_DIR, 'data', 'exercises-merged.json')
    with open(out_path, 'w', encoding='utf-8') as f:
        json.dump(output, f, ensure_ascii=False, indent=2)

    print(f'Merged: {len(existing_exercises)} existing + {len(converted)} new = {len(merged)} total')
    if untranslated:
        print(f'\nWARNING: {len(untranslated)} exercises without French translation:')
        for n in untranslated:
            print(f'  - {n}')
    else:
        print('All exercises translated to French!')

    # ── Generate exercise-images.ts ──
    # Build name_en → free-exercise-db ID mapping for ALL exercises
    # 1. For new exercises: use the native `id` field from free-exercise-db
    # 2. For existing 124: use manual overrides (our name_en often differs from free-exercise-db name)
    generate_image_mapping(new_exercises, existing_names)


# Manual overrides for our 124 enriched exercises whose name_en
# doesn't match the free-exercise-db directory name
MANUAL_IMAGE_OVERRIDES = {
    'Barbell Bench Press': 'Barbell_Bench_Press_-_Medium_Grip',
    'Incline Barbell Press': 'Barbell_Incline_Bench_Press_-_Medium_Grip',
    'Decline Press': 'Decline_Barbell_Bench_Press',
    'Floor Press': 'Dumbbell_Floor_Press',
    'High Cable Fly': 'Cable_Crossover',
    'Low Cable Fly': 'Low_Cable_Crossover',
    'Pec Deck Machine': 'Butterfly',
    'Machine Chest Press': 'Machine_Bench_Press',
    'Convergent Bench Press': 'Leverage_Chest_Press',
    'Convergent Incline Press': 'Leverage_Incline_Chest_Press',
    'Convergent Decline Press': 'Leverage_Decline_Chest_Press',
    'Push-ups': 'Pushups',
    'Chest Dips': 'Dips_-_Chest_Version',
    'Dumbbell Pullover': 'Bent-Arm_Dumbbell_Pullover',
    'Low Cable Pullover': 'Straight-Arm_Pulldown',
    'Barbell Row': 'Bent_Over_Barbell_Row',
    'Dumbbell Row': 'One-Arm_Dumbbell_Row',
    'Pendlay Row': 'Bent_Over_Barbell_Row',
    'T-Bar Row': 'T-Bar_Row_with_Handle',
    'Meadows Row': 'One-Arm_Dumbbell_Row',
    'Chest Supported Row': 'Dumbbell_Incline_Row',
    'Seated Cable Row': 'Seated_Cable_Rows',
    'Low Row Machine': 'Seated_Cable_Rows',
    'Convergent Row': 'Leverage_High_Row',
    'Lat Pulldown': 'Wide-Grip_Lat_Pulldown',
    'Convergent Lat Pulldown': 'Close-Grip_Front_Lat_Pulldown',
    'Reverse Grip Pulldown': 'Underhand_Cable_Pulldowns',
    'Pull-ups': 'Pullups',
    'Chin-ups': 'Chin-Up',
    'Assisted Pull-up Machine': 'Band_Assisted_Pull-Up',
    'Deadlift': 'Barbell_Deadlift',
    'Romanian Deadlift': 'Romanian_Deadlift',
    'Sumo Deadlift': 'Sumo_Deadlift',
    'Trap Bar Deadlift': 'Trap_Bar_Deadlift',
    'Single Leg Romanian Deadlift': 'Kettlebell_One-Legged_Deadlift',
    'Good Morning': 'Good_Morning',
    'Cable Pullover': 'Straight-Arm_Pulldown',
    'Face Pull': 'Face_Pull',
    'Overhead Press': 'Standing_Military_Press',
    'Seated Dumbbell Press': 'Seated_Dumbbell_Press',
    'Arnold Press': 'Arnold_Dumbbell_Press',
    'Landmine Press': 'Landmine_180s',
    'Convergent Shoulder Press': 'Leverage_Shoulder_Press',
    'Lateral Raises': 'Side_Lateral_Raise',
    'Cable Lateral Raise': 'Cable_Seated_Lateral_Raise',
    'Machine Lateral Raise': 'Seated_Side_Lateral_Raise',
    'Front Raises': 'Front_Dumbbell_Raise',
    'Cable Front Raise': 'Front_Cable_Raise',
    'Rear Delt Fly': 'Seated_Bent-Over_Rear_Delt_Raise',
    'Cable Rear Delt Fly': 'Cable_Rear_Delt_Fly',
    'Reverse Fly Machine': 'Reverse_Machine_Flyes',
    'Cable L-Fly': 'External_Rotation',
    'Upright Row': 'Upright_Barbell_Row',
    'Dumbbell Shrugs': 'Dumbbell_Shrug',
    'Clean and Press': 'Clean_and_Press',
    'Barbell Curl': 'Barbell_Curl',
    'Dumbbell Curl': 'Dumbbell_Bicep_Curl',
    'Incline Curl': 'Incline_Dumbbell_Curl',
    'Hammer Curl': 'Hammer_Curls',
    'Cable Hammer Curl': 'Cable_Hammer_Curls_-_Rope_Attachment',
    'Preacher Curl': 'Preacher_Curl',
    'Preacher Curl Machine': 'Machine_Preacher_Curls',
    'Cable Curl': 'High_Cable_Curls',
    'Cable Curl Face to Face': 'High_Cable_Curls',
    'Face Away Cable Curl': 'Overhead_Cable_Curl',
    'Concentration Curl': 'Concentration_Curls',
    'Reverse Curl': 'Reverse_Barbell_Curl',
    'Tricep Pushdown': 'Triceps_Pushdown',
    'Rope Pushdown': 'Triceps_Pushdown_-_Rope_Attachment',
    'Overhead Tricep Extension': 'Standing_Overhead_Barbell_Triceps_Extension',
    'Cable Overhead Triceps Extension': 'Cable_Rope_Overhead_Triceps_Extension',
    'Skull Crusher': 'Lying_Triceps_Press',
    'Close Grip Bench Press': 'Close-Grip_Barbell_Bench_Press',
    'Tricep Kickback': 'Tricep_Dumbbell_Kickback',
    'Cable Triceps Kickback': 'Cable_One_Arm_Tricep_Extension',
    'Tricep Dips': 'Dips_-_Triceps_Version',
    'Triceps Dip Machine': 'Machine_Triceps_Extension',
    'Assisted Dip Machine': 'Dip_Machine',
    'Barbell Squat': 'Barbell_Full_Squat',
    'Front Squat': 'Front_Barbell_Squat',
    'Goblet Squat': 'Goblet_Squat',
    'Hack Squat': 'Hack_Squat',
    'Smith Machine Squat': 'Smith_Machine_Squat',
    'Pendulum Squat': 'Hack_Squat',
    'Belt Squat Machine': 'Hack_Squat',
    'Sissy Squat': 'Weighted_Sissy_Squat',
    'Leg Press': 'Leg_Press',
    'Vertical Leg Press': 'Smith_Machine_Leg_Press',
    'Leg Extension': 'Leg_Extensions',
    'Bulgarian Split Squat': 'Split_Squats',
    'Walking Lunges': 'Barbell_Walking_Lunge',
    'Forward Lunges': 'Dumbbell_Lunges',
    'Lying Leg Curl': 'Lying_Leg_Curls',
    'Seated Leg Curl': 'Seated_Leg_Curl',
    'Hip Thrust': 'Barbell_Hip_Thrust',
    'Glute Bridge': 'Barbell_Glute_Bridge',
    'Cable Glute Kickback': 'Glute_Kickback',
    'Kettlebell Swing': 'One-Arm_Kettlebell_Swings',
    'Adductor Machine': 'Thigh_Adductor',
    'Abductor Machine': 'Thigh_Abductor',
    'Seated Hip Adductor Machine': 'Thigh_Adductor',
    'Seated Hip Abductor Machine': 'Thigh_Abductor',
    'Cable Hip Adduction': 'Cable_Hip_Adduction',
    'Cable Hip Abduction': 'Thigh_Abductor',
    'Standing Calf Raise': 'Standing_Calf_Raises',
    'Standing Calf Machine': 'Smith_Machine_Calf_Raise',
    'Seated Calf Raise': 'Seated_Calf_Raise',
    'Crunch': 'Crunches',
    'Reverse Crunch': 'Reverse_Crunch',
    'Cable Crunch': 'Cable_Crunch',
    'Hanging Leg Raise': 'Hanging_Leg_Raise',
    'Plank': 'Plank',
    'Side Plank': 'Plank',
    'Ab Wheel Rollout': 'Ab_Roller',
    'Russian Twist': 'Russian_Twist',
    'Cable Woodchop': 'Standing_Cable_Wood_Chop',
    'Cable Pallof Press': 'Pallof_Press_With_Rotation',
    'Dead Bug': 'Dead_Bug',
    'Mountain Climbers': 'Mountain_Climbers',
    'Burpees': 'Box_Jump_Multiple_Response',
}


def generate_image_mapping(source_exercises, existing_names):
    """Generate exercise-images.ts with mapping for all exercises."""
    # Build name → id from free-exercise-db source data
    source_map = {}
    for ex in source_exercises:
        source_map[ex['name']] = ex['id']

    # Start with manual overrides (for our 124 enriched exercises)
    mapping = dict(MANUAL_IMAGE_OVERRIDES)

    # Add all free-exercise-db exercises (name → native id)
    for ex in source_exercises:
        name = ex['name']
        if name not in mapping:
            mapping[name] = ex['id']

    ts_path = os.path.join(APP_DIR, 'src', 'lib', 'exercise-images.ts')
    lines = [
        '/**',
        ' * Auto-generated by scripts/build-exercises-merged.py',
        ' * Maps exercise English names to free-exercise-db image directory IDs.',
        ' * Do not edit manually — run: python3 scripts/build-exercises-merged.py',
        ' */',
        '',
        'const IMAGE_MAP: Record<string, string> = {',
    ]
    for name in sorted(mapping.keys()):
        img_id = mapping[name]
        escaped_name = name.replace("'", "\\'")
        escaped_id = img_id.replace("'", "\\'")
        lines.append(f"  '{escaped_name}': '{escaped_id}',")
    lines.append('};')
    lines.append('')
    lines.append("const BASE_URL = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises';")
    lines.append('')
    lines.append('/**')
    lines.append(' * Get image URLs for an exercise (typically 2 images: start and end position).')
    lines.append(' */')
    lines.append('export function getExerciseImages(exerciseNameEn: string | null): string[] {')
    lines.append('  if (!exerciseNameEn) return [];')
    lines.append('  const id = IMAGE_MAP[exerciseNameEn];')
    lines.append('  if (!id) return [];')
    lines.append('  return [`${BASE_URL}/${id}/0.jpg`, `${BASE_URL}/${id}/1.jpg`];')
    lines.append('}')
    lines.append('')
    lines.append('/**')
    lines.append(' * Get the primary (start position) image URL for an exercise.')
    lines.append(' */')
    lines.append('export function getExerciseImage(exerciseNameEn: string | null): string | null {')
    lines.append('  const images = getExerciseImages(exerciseNameEn);')
    lines.append('  return images[0] ?? null;')
    lines.append('}')
    lines.append('')
    lines.append('/**')
    lines.append(' * Check if images are available for an exercise.')
    lines.append(' */')
    lines.append('export function hasExerciseImages(exerciseNameEn: string | null): boolean {')
    lines.append('  return !!exerciseNameEn && exerciseNameEn in IMAGE_MAP;')
    lines.append('}')
    lines.append('')

    with open(ts_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print(f'Generated {ts_path} with {len(mapping)} image mappings')


if __name__ == '__main__':
    main()
